// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

import { ActionKind, Tone, type Action, type Surface } from "./contract.gen.js";
import { compose, Prop, Slot, type El, type Elish, type Element, type Props } from "./ui_runtime.js";
import { bind } from "./binding.js";

export { Group, ID, Prop, Slot, When, Element } from "./ui_runtime.js";
export type { El, Elish, Props } from "./ui_runtime.js";
export { ActionKind, Surface, Tone } from "./contract.gen.js";
export { bind, isBinding, bindingPath, bindingMarker } from "./binding.js";
export type { Binding } from "./binding.js";
export type { Action, UINode } from "./contract.gen.js";

// ── primitives ─────────────────────────────────────────────────────────────
// The native tier: node types a client implements itself (ADR 0024).

/** Box is the layout container every composition is built from.
 *
 *  Native: The irreducible layout leaf. A definition is a tree of primitives, so the base case cannot itself be a definition. It also resolves style.responsive against the live viewport, and visibleWhen against the live State scope — two render-time branches no static tree can carry. */
export function Box(...els: Elish[]): Element {
  return compose("Box", undefined, els);
}

/** Text renders a run of text in a token style. Children render after the text, for inline nesting.
 *
 *  Native: The irreducible text leaf. */
export function Text(...els: Elish[]): Element {
  return compose("Text", undefined, els);
}

/** Image renders a remote or proxied image with a placeholder fallback.
 *
 *  Native: Loading a resource, handling decode failure and falling back to a placeholder are client behaviours. It also feeds the art-light sampler, which reads decoded pixels. */
export function Image(...els: Elish[]): Element {
  return compose("Image", undefined, els);
}

/** Icon renders one glyph from the client's bundled icon set.
 *
 *  Native: Resolves a name to a vector the client ships. The glyph set is a client asset, not data. */
export function Icon(...els: Elish[]): Element {
  return compose("Icon", undefined, els);
}

/** Pressable makes its subtree activate an Action.
 *
 *  Native: Turning a pointer, key or remote-control event into an Action dispatch is client behaviour. */
export function Pressable(...els: Elish[]): Element {
  return compose("Pressable", undefined, els);
}

/** Spacer occupies empty space in a stack, fixed or growing.
 *
 *  Native: An irreducible layout leaf. */
export function Spacer(...els: Elish[]): Element {
  return compose("Spacer", undefined, els);
}

/** Fragment renders its children with no wrapper of its own.
 *
 *  Native: A transparent grouping node the expander needs in order to return several nodes where one is expected. */
export function Fragment(...els: Elish[]): Element {
  return compose("Fragment", undefined, els);
}

/** Outlet marks the point in a definition's template where the caller's slot content is substituted.
 *
 *  Native: It is the definition expander's own mechanism. A definition defined in terms of Outlet cannot itself be expanded without it, so it must be native. */
export function Outlet(...els: Elish[]): Element {
  return compose("Outlet", undefined, els);
}

/** NavItem is one entry in the app frame's navigation.
 *
 *  Native: Owns active-route state: it compares the current screen against its own target, which only the client knows. */
export function NavItem(...els: Elish[]): Element {
  return compose("NavItem", undefined, els);
}

/** NavBar groups NavItems into the frame's responsive navigation.
 *
 *  Native: Presents as an inline bar or a bottom tab strip depending on the viewport — a render-time branch, not data. */
export function NavBar(...els: Elish[]): Element {
  return compose("NavBar", undefined, els);
}

/** Tabs shows one panel at a time behind a tab strip. Each tab's content goes in the named slot matching its id, not in the ordered child list — an ordered child is dropped.
 *
 *  Native: Owns the active tab index. */
export function Tabs(...els: Elish[]): Element {
  return compose("Tabs", undefined, els);
}

/** Rotator cross-fades through its children on a timer.
 *
 *  Native: Owns a timer and derives the active index from it, and republishes the active slide's palette to the acrylic surfaces. */
export function Rotator(...els: Elish[]): Element {
  return compose("Rotator", undefined, els);
}

/** State declares named variables and scopes them to its subtree. Children bind to them by name, and a setValue action writes them.
 *
 *  Native: It holds values across renders. A tree is a description of one moment; something has to remember what was typed between two of them, and no arrangement of static nodes can. It is also the scope boundary itself — which of two enclosing States a name resolves to is a question only the renderer, walking its own tree, can answer. */
export function State(...els: Elish[]): Element {
  return compose("State", undefined, els);
}

/** TextInput is a bare text entry field.
 *
 *  Native: Owns its input value between keystroke and submission. */
export function TextInput(...els: Elish[]): Element {
  return compose("TextInput", undefined, els);
}

/** Switch is a bare on/off control.
 *
 *  Native: Owns its on/off state. */
export function Switch(...els: Elish[]): Element {
  return compose("Switch", undefined, els);
}

/** SelectInput is a bare dropdown.
 *
 *  Native: Owns its selected value. */
export function SelectInput(...els: Elish[]): Element {
  return compose("SelectInput", undefined, els);
}

/** SearchBar is the frame's persistent search entry.
 *
 *  Native: The submitted action must carry the live input value, and in a live session the value streams up debounced as it changes. */
export function SearchBar(...els: Elish[]): Element {
  return compose("SearchBar", undefined, els);
}

/** Menu is a click-to-open list of actions behind a trigger.
 *
 *  Native: Owns its open/closed state. */
export function Menu(...els: Elish[]): Element {
  return compose("Menu", undefined, els);
}

/** Slider selects a number in a range.
 *
 *  Native: Displays its own live value beside itself, so output couples to internal state. */
export function Slider(...els: Elish[]): Element {
  return compose("Slider", undefined, els);
}

/** RatingControl selects a star rating.
 *
 *  Native: Owns the selection. */
export function RatingControl(...els: Elish[]): Element {
  return compose("RatingControl", undefined, els);
}

/** SeasonSelector picks one season of a series.
 *
 *  Native: Owns the selected season. */
export function SeasonSelector(...els: Elish[]): Element {
  return compose("SeasonSelector", undefined, els);
}

/** ProgressBar shows a linear completion fraction.
 *
 *  Native: Fill geometry is computed from the value at render. */
export function ProgressBar(...els: Elish[]): Element {
  return compose("ProgressBar", undefined, els);
}

/** ProgressRing shows a circular completion fraction with the percentage inside.
 *
 *  Native: Arc geometry is computed from the value at render. */
export function ProgressRing(...els: Elish[]): Element {
  return compose("ProgressRing", undefined, els);
}

/** Skeleton is an animated loading placeholder.
 *
 *  Native: Expands to a repeated animated shape; the animation is a client concern. */
export function Skeleton(...els: Elish[]): Element {
  return compose("Skeleton", undefined, els);
}

/** Player is the playback surface.
 *
 *  Native: The client owns the decoding pipeline and the transport controls (ADR 0047, ADR 0070). A scrub bar cannot be driven over a network at frame rate. */
export function Player(src: string, ...els: Elish[]): Element {
  return compose("Player", { src }, els);
}

// ── components ─────────────────────────────────────────────────────────────

/** Screen is the root of a server-defined page. */
export function Screen(...els: Elish[]): Element {
  return compose("Screen", undefined, els);
}

/** Section is a titled band. */
export function Section(title: string, ...els: Elish[]): Element {
  return compose("Section", { title }, els);
}

/** Carousel is a horizontal snap-scrolling rail. */
export function Carousel(...els: Elish[]): Element {
  return compose("Carousel", undefined, els);
}

/** Grid is a responsive auto-fill grid. */
export function Grid(...els: Elish[]): Element {
  return compose("Grid", undefined, els);
}

/** Stack arranges children; direction is "horizontal" or "vertical". */
export function Stack(direction: string, gap: number, ...els: Elish[]): Element {
  return compose("Stack", { direction, gap }, els);
}

/** Hero is a featured banner. Fill its call-to-action row with Actions. */
export function Hero(title: string, ...els: Elish[]): Element {
  return compose("HeroBanner", { title }, els);
}

/** PosterCard renders a work/item card. */
export function PosterCard(title: string, mediaType: string, ...els: Elish[]): Element {
  return compose("PosterCard", { title, mediaType }, els);
}

/** Button carries an action; variant is primary/secondary/ghost/danger. */
export function Button(label: string, variant: string, ...els: Elish[]): Element {
  return compose("Button", { label, variant }, els);
}

/** Badge is a small pill; tone is one of the Tone values. */
export function Badge(label: string, tone: string, ...els: Elish[]): Element {
  return compose("Badge", { label, tone }, els);
}

/** Banner is an inline message; tone is one of the Tone values. */
export function Banner(message: string, tone: string, ...els: Elish[]): Element {
  return compose("Banner", { message, tone }, els);
}

/** DetailHeader renders a node's metadata (title, meta, genres). */
export function DetailHeader(title: string, ...els: Elish[]): Element {
  return compose("DetailHeader", { title }, els);
}

/** EpisodeRow renders one episode under a season. */
export function EpisodeRow(title: string, ...els: Elish[]): Element {
  return compose("EpisodeRow", { title }, els);
}

/** PersonChip is a cast/crew chip. */
export function PersonChip(name: string, ...els: Elish[]): Element {
  return compose("PersonChip", { name }, els);
}

/** GenreTag is a genre chip. */
export function GenreTag(label: string, ...els: Elish[]): Element {
  return compose("GenreTag", { label }, els);
}

/** FilterChip is one selectable narrowing on a browse surface: a pressable pill that draws its own selected state, with an optional count of what it would leave. */
export function FilterChip(label: string, selected: boolean, ...els: Elish[]): Element {
  return compose("FilterChip", { label, selected }, els);
}

/** EmptyState is a titled empty placeholder, with an optional explanation beneath it and a call to action. */
export function EmptyState(icon: string, title: string, ...els: Elish[]): Element {
  return compose("EmptyState", { icon, title }, els);
}

/** AppShell is the application frame (ADR 0031): the brand bar, the nav and the region the current screen renders into. */
export function AppShell(title: string, ...els: Elish[]): Element {
  return compose("AppShell", { title }, els);
}

/** DetailHero is a title's cinematic header — backdrop, logo and the actions docked over it. */
export function DetailHero(title: string, ...els: Elish[]): Element {
  return compose("DetailHero", { title }, els);
}

/** Divider is a rule, optionally labelled. */
export function Divider(...els: Elish[]): Element {
  return compose("Divider", undefined, els);
}

/** ErrorState renders a Platform error category as something a person can act on. */
export function ErrorState(category: string, ...els: Elish[]): Element {
  return compose("ErrorState", { category }, els);
}

/** ExtensionCard is one extension module — what it is, what it can do, and where its bytes come from (ADR 0081). */
export function ExtensionCard(name: string, ...els: Elish[]): Element {
  return compose("ExtensionCard", { name }, els);
}

/** IconButton is a Button reduced to its icon; the label stays for assistive tech. */
export function IconButton(icon: string, label: string, variant: string, ...els: Elish[]): Element {
  return compose("IconButton", { icon, label, variant }, els);
}

/** InfoPanel is a docked facts panel — a rating and a run of label/value rows. The mockups draw a control under it ("Change device"); it is not here because Mosaic has no device registry to change between, and a panel is the wrong place to learn that. */
export function InfoPanel(...els: Elish[]): Element {
  return compose("InfoPanel", undefined, els);
}

/** FactCard is one labelled card in a row of technical facts — what a release is, how it will be delivered, where its metadata came from. Distinct from InfoPanel because the shape is different and so is the job: a panel answers about the title in label/value pairs, a card states three short facts about one aspect of it and sits in a grid of siblings. */
export function FactCard(label: string, ...els: Elish[]): Element {
  return compose("FactCard", { label }, els);
}

/** MediaTile is a landscape card for episodes and continue-watching. */
export function MediaTile(title: string, ...els: Elish[]): Element {
  return compose("MediaTile", { title }, els);
}

/** Pagination is a prev/next pair. The server supplies both targets; the client does no arithmetic. */
export function Pagination(...els: Elish[]): Element {
  return compose("Pagination", undefined, els);
}

/** PlaybackBar is the resume strip for something already started. */
export function PlaybackBar(title: string, ...els: Elish[]): Element {
  return compose("PlaybackBar", { title }, els);
}

/** RelatedRail is a titled rail that says so when it is empty. */
export function RelatedRail(title: string, ...els: Elish[]): Element {
  return compose("RelatedRail", { title }, els);
}

/** Select is a labelled dropdown over server-supplied options. */
export function Select(label: string, ...els: Elish[]): Element {
  return compose("Select", { label }, els);
}

/** SettingsFrame is the Platform-owned settings chrome (ADR 0038): a nav beside the panel the open section fills. */
export function SettingsFrame(title: string, ...els: Elish[]): Element {
  return compose("SettingsFrame", { title }, els);
}

/** SpanRow is one span of a waterfall: its name, indented by depth, a bar showing its share of the whole, and its duration. The share is the point — a waterfall exists to answer which part of this was the time, and a duration alone does not. */
export function SpanRow(title: string, ...els: Elish[]): Element {
  return compose("SpanRow", { title }, els);
}

/** DetailPanel is a titled working surface: a header carrying a name, an identifier and a summary, over a body. Flat rather than acrylic — it is the administrative side of the app, where there is no artwork behind the surface for the material to bend. */
export function DetailPanel(title: string, ...els: Elish[]): Element {
  return compose("DetailPanel", { title }, els);
}

/** StatCard is one figure with a name over it — a percentile, an error rate, a throughput. Distinct from FactCard, which states three short sentences about an aspect of something; this states one number and exists to be scanned in a row of its siblings. */
export function StatCard(label: string, value: string, ...els: Elish[]): Element {
  return compose("StatCard", { label, value }, els);
}

/** LogTable is a run of structured records as a table — time, level, service, message and the trace that produced it, in fixed columns. A table rather than a stack of cards because the columns are how you read a log: the eye runs down one of them looking for the line that is different. */
export function LogTable(...els: Elish[]): Element {
  return compose("LogTable", undefined, els);
}

/** LatencyHistogram is a distribution as bars — where the time actually went, which a set of percentiles summarises and cannot show. Bars carry their own count and label; the server sizes them, because only it knows what the tallest bucket is. */
export function LatencyHistogram(label: string, ...els: Elish[]): Element {
  return compose("LatencyHistogram", { label }, els);
}

/** TraceRow is one trace in a list: what ran, its id, how long it took, and a status dot when something inside it failed. */
export function TraceRow(title: string, ...els: Elish[]): Element {
  return compose("TraceRow", { title }, els);
}

/** SettingsRow is one line of a settings panel — a label, an optional explanation of what it does, and a control or a value on the right. It is the workhorse of every panel in the design, which is why it is a component rather than a Stack assembled per screen: a panel that builds its own rows is a panel that drifts from the others. */
export function SettingsRow(label: string, ...els: Elish[]): Element {
  return compose("SettingsRow", { label }, els);
}

/** SettingsNavGroup is one labelled run of settings nav rows. */
export function SettingsNavGroup(label: string, ...els: Elish[]): Element {
  return compose("SettingsNavGroup", { label }, els);
}

/** SettingsNavItem is one settings nav row. The server marks the active one — it is the side that knows the params (ADR 0039). */
export function SettingsNavItem(label: string, icon: string, ...els: Elish[]): Element {
  return compose("SettingsNavItem", { label, icon }, els);
}

/** SourcePicker lists the resolved sources for a Part. */
export function SourcePicker(...els: Elish[]): Element {
  return compose("SourcePicker", undefined, els);
}

/** StatusIndicator is a coloured dot with a label. */
export function StatusIndicator(label: string, tone: string, ...els: Elish[]): Element {
  return compose("StatusIndicator", { label, tone }, els);
}

/** TextField is a labelled text input with optional help. */
export function TextField(label: string, ...els: Elish[]): Element {
  return compose("TextField", { label }, els);
}

/** Toggle is a switch with a label. It carries the value it moves TO — the client reports the flip, the server decides what it means. */
export function Toggle(label: string, ...els: Elish[]): Element {
  return compose("Toggle", { label }, els);
}

/** Form is a State scope with a submit control: it declares the fields' variables, hosts them, and emits its submit action with their values merged in. Composed rather than native — it is a State, an Outlet and a button, and nothing about it needs client code. */
export function Form(...els: Elish[]): Element {
  return compose("Form", undefined, els);
}

/** Component is the generic constructor for a type without a helper (a standard component like SeasonSelector, or a module's own). */
export function Component(typ: string, ...els: Elish[]): Element {
  return compose(typ, undefined, els);
}

// ── slots ──────────────────────────────────────────────────────────────────

/** Actions fills the "actions" slot (a hero's CTA row). */
export function Actions(...els: Elish[]): El {
  return Slot("actions", ...els);
}

/** Aside fills the "aside" slot (a hero's docked poster). */
export function Aside(...els: Elish[]): El {
  return Slot("aside", ...els);
}

/** ActionSlot fills the "action" slot (an empty state's call to action). */
export function ActionSlot(...els: Elish[]): El {
  return Slot("action", ...els);
}

/** Header fills a screen's "header" slot. */
export function Header(...els: Elish[]): El {
  return Slot("header", ...els);
}

/** Bleed fills a screen's edge-to-edge "bleed" slot (a cinematic hero). */
export function Bleed(...els: Elish[]): El {
  return Slot("bleed", ...els);
}

/** Rail fills a hero's "rail" slot. */
export function Rail(...els: Elish[]): El {
  return Slot("rail", ...els);
}

/** Tags fills a hero's "tags" slot. */
export function Tags(...els: Elish[]): El {
  return Slot("tags", ...els);
}

/** Nav fills a frame's "nav" slot. */
export function Nav(...els: Elish[]): El {
  return Slot("nav", ...els);
}

/** Footer fills a frame's "footer" slot (level controls, not sections). */
export function Footer(...els: Elish[]): El {
  return Slot("footer", ...els);
}

/** Content fills the app frame's "content" region — where the current screen renders. */
export function Content(...els: Elish[]): El {
  return Slot("content", ...els);
}

/** TopBar fills the app frame's "topbar" slot. */
export function TopBar(...els: Elish[]): El {
  return Slot("topbar", ...els);
}

/** Account fills the app frame's "account" slot. */
export function Account(...els: Elish[]): El {
  return Slot("account", ...els);
}

// ── sugar ──────────────────────────────────────────────────────────────────

/** OnTap sets the node's primary action. */
export function OnTap(v: Action): El {
  return Prop("action", v);
}

/** FacetCount sets how many items a narrowing would leave, shown inside the chip that offers it. A string rather than a number because it is a label: the count is formatted where the fact is known, and a chip is not the place to decide how a large number reads. */
export function FacetCount(v: string): El {
  return Prop("count", v);
}

/** Title sets a screen or component title. */
export function Title(v: string): El {
  return Prop("title", v);
}

/** Subtitle sets a card/row subtitle. */
export function Subtitle(v: string): El {
  return Prop("subtitle", v);
}

/** Poster sets a poster image URL. */
export function Poster(v: string): El {
  return Prop("poster", v);
}

/** Backdrop sets a hero backdrop image URL. */
export function Backdrop(v: string): El {
  return Prop("backdrop", v);
}

/** Logo sets a hero clearlogo/title-treatment image URL. */
export function Logo(v: string): El {
  return Prop("logo", v);
}

/** Overview sets a synopsis/overview string. */
export function Overview(v: string): El {
  return Prop("overview", v);
}

/** Message sets the explanation beneath an empty or error state's title. Banner takes its message positionally; every other component that carries one needs this, and without it the emit-side sets the key by string — which is how a prop nothing renders gets shipped. */
export function Message(v: string): El {
  return Prop("message", v);
}

/** Progress sets a 0..1 watched fraction. */
export function Progress(v: number): El {
  return Prop("progress", v);
}

/** BadgeText sets a corner badge on a card. */
export function BadgeText(v: string): El {
  return Prop("badge", v);
}

/** ActionLabel sets a Section's "see all" action label (paired with OnTap). */
export function ActionLabel(v: string): El {
  return Prop("actionLabel", v);
}

/** Meta sets a hero's meta line (year, type, rating). */
export function Meta(...v: string[]): El {
  return Prop("meta", v);
}

/** Genres sets a DetailHeader's genre list. */
export function Genres(...v: string[]): El {
  return Prop("genres", v);
}

/** ResumeAt sets the position in seconds a Player starts from (ADR 0046). */
export function ResumeAt(v: number): El {
  return Prop("resumeAt", v);
}

/** MimeType sets the media type a Player should expect, so a client can pick a pipeline before it fetches. */
export function MimeType(v: string): El {
  return Prop("mimeType", v);
}

/** NodeID names the item a Player is playing, so the client can report its position back against it (ADR 0046). */
export function NodeID(v: string): El {
  return Prop("nodeId", v);
}

/** PartID names the release a Player is playing, recorded with the position so a resume returns to the same encode (ADR 0046). */
export function PartID(v: string): El {
  return Prop("partId", v);
}

/** Disabled greys a control and stops it emitting. */
export function Disabled(v: boolean): El {
  return Prop("disabled", v);
}

/** IconName names the glyph a control or row shows. It is not called Icon because Icon is the primitive that renders a glyph as a node of its own; this sets the `icon` prop of something that draws one. */
export function IconName(v: string): El {
  return Prop("icon", v);
}

/** ItemWidth fixes a carousel's track width in px. */
export function ItemWidth(v: number): El {
  return Prop("itemWidth", v);
}

/** Gap sets the space token between a container's children. Stack takes it positionally; a Grid that wants something other than its default says so with this. */
export function Gap(v: number): El {
  return Prop("gap", v);
}

/** MinColumnWidth is a grid's smallest column before it reflows, in px. */
export function MinColumnWidth(v: number): El {
  return Prop("minColumnWidth", v);
}

/** Rating sets a displayed score. */
export function Rating(v: string): El {
  return Prop("rating", v);
}

/** RatingLabel is the source a rating came from. */
export function RatingLabel(v: string): El {
  return Prop("ratingLabel", v);
}

/** Year sets a release year. */
export function Year(v: string): El {
  return Prop("year", v);
}

/** Index is an episode's place in its series as the design writes it — "S2 E7". A string rather than the episode number, because the season is half the answer and a row that says only "7" is ambiguous the moment a season control sits above it. */
export function Index(v: string): El {
  return Prop("index", v);
}

/** Runtime is a human-readable duration. */
export function Runtime(v: string): El {
  return Prop("runtime", v);
}

/** Thumbnail sets a row's still image. */
export function Thumbnail(v: string): El {
  return Prop("thumbnail", v);
}

/** Watched marks an episode as already seen. */
export function Watched(v: boolean): El {
  return Prop("watched", v);
}

/** Credits sets a hero's crew line — "Created by X · Directed by Y". One string rather than a list, because it is one sentence with the source's own separators in it; a list would make the joiner a client decision and the client has no way to know whether "and" or "·" is right. */
export function Credits(v: string): El {
  return Prop("credits", v);
}

/** Quality is a release's resolution and dynamic range as one phrase — "4K HDR", "1080p". Display-only: it names what a viewer would recognise, not what a decision engine ranks on. */
export function Quality(v: string): El {
  return Prop("quality", v);
}

/** Lines are a fact card's body, one short statement per line. Separate from Meta because Meta's entries are pills on one row and these are stacked sentences. */
export function Lines(...v: string[]): El {
  return Prop("lines", v);
}

/** Compact is the search screen's heading treatment: a small uppercase label rather than a title, and the heading itself becomes the way into the thing it names. One flag because it is one treatment — a results group is labelled, counted and entered from the same line. */
export function Compact(v: boolean): El {
  return Prop("compact", v);
}

/** PinAction keeps a Section's onward link visible instead of revealing it on hover. A rail whose heading is the only way into a catalog cannot hide that link behind a pointer, which no remote control has. */
export function PinAction(v: boolean): El {
  return Prop("pinAction", v);
}

/** Kicker is the eyebrow line above a hero's title. */
export function Kicker(v: string): El {
  return Prop("kicker", v);
}

/** NativeTitle is the original-language title shown beside the localised one. */
export function NativeTitle(v: string): El {
  return Prop("nativeTitle", v);
}

/** ProgressLabel describes progress in words ("24m left"). */
export function ProgressLabel(v: string): El {
  return Prop("progressLabel", v);
}

/** ShowTags reveals a hero's tag row. */
export function ShowTags(v: boolean): El {
  return Prop("showTags", v);
}

/** OverlayTitle lays a tile's title over its artwork instead of beneath it, for a card that is mostly image — the hero's up-next dock. Off by default, because a title on the picture is only legible when the tile is large enough to carry a scrim under it. */
export function OverlayTitle(v: boolean): El {
  return Prop("overlayTitle", v);
}

/** Avatar sets a person's portrait. */
export function Avatar(v: string): El {
  return Prop("avatar", v);
}

/** Role is a person's part — a character, or a crew credit. */
export function Role(v: string): El {
  return Prop("role", v);
}

/** Align sets a stack's cross-axis alignment. */
export function Align(v: string): El {
  return Prop("align", v);
}

/** Justify sets a stack's main-axis distribution. */
export function Justify(v: string): El {
  return Prop("justify", v);
}

/** Wrap lets a stack run onto more than one line. */
export function Wrap(v: boolean): El {
  return Prop("wrap", v);
}

/** Retry is what an error state's try-again control emits. */
export function Retry(v: Action): El {
  return Prop("retry", v);
}

/** Share is how much of a whole a bar represents, as a percentage the server computed. The server sizes it because only it knows what the whole is. */
export function Share(v: string): El {
  return Prop("share", v);
}

/** Depth is a row's level in a tree, as a space token to indent by. Distinct from Indent, which is a bool saying a nav row is nested under the one above it: one is how far, the other is whether. */
export function Depth(v: number): El {
  return Prop("depth", v);
}

/** Buckets are a histogram's bars — each a label, a count and the height the server sized it to. */
export function Buckets(v: Props[]): El {
  return Prop("buckets", v);
}

/** StatusTone is the colour a row's status marker takes, named as a colour token because the server decides what a level or a status means and the client only draws it. Named StatusTone rather than Tone because the TypeScript binding already exports a `Tone` *type* — the tones enum — and a helper of the same name shadows it. */
export function StatusTone(v: string): El {
  return Prop("tone", v);
}

/** Rows are an info panel's label/value pairs. */
export function Rows(v: Props[]): El {
  return Prop("rows", v);
}

/** Sources are the resolved streams a picker offers. */
export function Sources(v: Props[]): El {
  return Prop("sources", v);
}

/** Options are a select's choices. */
export function Options(v: Props[]): El {
  return Prop("options", v);
}

/** Capabilities are the provider roles a module declares, as chips. */
export function Capabilities(v: Props[]): El {
  return Prop("capabilities", v);
}

/** Summary is a card's one-line description. */
export function Summary(v: string): El {
  return Prop("summary", v);
}

/** Value is a field's current value. */
export function Value(v: string): El {
  return Prop("value", v);
}

/** Placeholder is a field's empty-state hint. */
export function Placeholder(v: string): El {
  return Prop("placeholder", v);
}

/** Help is the note under a field. */
export function Help(v: string): El {
  return Prop("help", v);
}

/** InputType selects the keyboard/validation a field asks for. */
export function InputType(v: string): El {
  return Prop("inputType", v);
}

/** Validators are the rules a client enforces before it submits — the six the contract declares, no more. A server rejection lands in the same slot (ADR 0089), so this is the fast half of one statement rather than the whole of it. It is sugar because a field's rules were being set with ui.Prop("validators", …) at every call site in every module, which is precisely the untyped setting that let ui.Subtitle onto a Stack. */
export function Validators(v: Props): El {
  return Prop("validators", v);
}

/** VisibleWhen hides a node until a predicate over the enclosing State scope holds. Absent means visible; unreadable means hidden, because a control shown because its rule could not be read is the fail-open case. */
export function VisibleWhen(v: Props): El {
  return Prop("visibleWhen", v);
}

/** FieldLabel names a field's control. Named FieldLabel rather than Label because every other component that carries a label takes it positionally — ui.Button(label, …) — and a second, optional way to set the same key on those would be two spellings of one prop. */
export function FieldLabel(v: string): El {
  return Prop("label", v);
}

/** Chrome selects which frame the app shell draws: "media" — the floating pills over a full-bleed hero — or "admin", the solid bar the settings side of the app wears. Named rather than a boolean because the two are different rooms in the same building, and a third (a player, a setup wizard) is a case rather than a second flag. */
export function Chrome(v: string): El {
  return Prop("chrome", v);
}

/** Breadcrumb is the trail after the brand in the admin chrome — "/ Settings". It says where you are on a side of the app that has no hero to say it for you. */
export function Breadcrumb(v: string): El {
  return Prop("breadcrumb", v);
}

/** Lead is the sentence under a panel's heading saying what the panel is for. Distinct from Summary, which explains one row. */
export function Lead(v: string): El {
  return Prop("lead", v);
}

/** Heading titles a frame's panel. */
export function Heading(v: string): El {
  return Prop("heading", v);
}

/** Selected says a section was asked for rather than defaulted to — what lets one payload drill down on a phone and show two panes on a desktop. */
export function Selected(v: boolean): El {
  return Prop("selected", v);
}

/** Indent nests a nav row under the one above it — an installed extension beneath the store it came from. One list that reads as a hierarchy rather than two lists. */
export function Indent(v: boolean): El {
  return Prop("indent", v);
}

/** Active marks the open nav row. */
export function Active(v: boolean): El {
  return Prop("active", v);
}

/** HasPrev enables a pagination's previous control. */
export function HasPrev(v: boolean): El {
  return Prop("hasPrev", v);
}

/** HasNext enables a pagination's next control. */
export function HasNext(v: boolean): El {
  return Prop("hasNext", v);
}

/** PrevAction is what a pagination's previous control emits. */
export function PrevAction(v: Action): El {
  return Prop("prevAction", v);
}

/** NextAction is what a pagination's next control emits. */
export function NextAction(v: Action): El {
  return Prop("nextAction", v);
}

/** On is a switch's state. Distinct from Value, which is a field's text: one prop key cannot be a string in one component and a boolean in another, and a switch that read \"true\" as text would render on for the string \"false\" too. */
export function On(v: boolean): El {
  return Prop("on", v);
}

/** Origin is where a thing came from — an extension's id, version and repository. Distinct from Meta, which is a hero's variadic meta line: the same key cannot be a string in one component and a list in another. */
export function Origin(v: string): El {
  return Prop("origin", v);
}

/** Vars declares a State scope's variables — each a name, a type ("string", "number" or "boolean") and an initial value. Declared rather than inferred: a client must know a name exists before anything writes to it, and must know what to coerce a written value to. */
export function Vars(v: Props[]): El {
  return Prop("vars", v);
}

/** Name is a field's name in the enclosing State scope. */
export function Name(v: string): El {
  return Prop("name", v);
}

/** SubmitAction is what a Form emits when it is submitted, with the scope's values merged into its input. */
export function SubmitAction(v: Action): El {
  return Prop("submitAction", v);
}

/** SubmitLabel is the text on a form's submit control. */
export function SubmitLabel(v: string): El {
  return Prop("submitLabel", v);
}

/** Busy marks a form as awaiting its submission's result. */
export function Busy(v: boolean): El {
  return Prop("busy", v);
}

/** Error is a form-level failure message, distinct from a field's own. */
export function Error(v: string): El {
  return Prop("error", v);
}

/** OnAppear is emitted the first time this node becomes visible on screen. The server decides what that means by choosing the action; a client never reports anything it was not asked to. */
export function OnAppear(v: Action): El {
  return Prop("onAppear", v);
}

/** OnDisappear is emitted when this node leaves the screen, having been visible. */
export function OnDisappear(v: Action): El {
  return Prop("onDisappear", v);
}

/** A11yLabel is the accessible name, for when the visible content is not one — an icon-only control, an image that carries meaning. It is deliberately not `label`: a visible label and an accessible name are different things, and one key meaning both is how a control ends up announced as its own caption. */
export function A11yLabel(v: string): El {
  return Prop("a11yLabel", v);
}

/** HeadingLevel is 1-6, the depth of a heading in the screen's outline. Stated rather than inferred from text size, because size is a design decision and outline depth is a structural one — and a screen reader navigates the second. */
export function HeadingLevel(v: number): El {
  return Prop("headingLevel", v);
}

/** Live marks a region whose changes should be announced: "polite" waits for a pause, "assertive" interrupts. Anything else is not announced. */
export function Live(v: string): El {
  return Prop("live", v);
}

/** Focusable marks a node that can take focus. Stated rather than inferred from interactivity: a card that navigates is focusable, and so is a heading a TV viewer needs to land on to read, and only the emit-side knows which. */
export function Focusable(v: boolean): El {
  return Prop("focusable", v);
}

/** FocusGroup makes this node's focusable descendants one stop in the tab order, moved between with the arrow keys — the roving pattern. A rail of forty cards is one stop, not forty. */
export function FocusGroup(v: boolean): El {
  return Prop("focusGroup", v);
}

/** InitialFocus asks for focus when this node first appears. At most one per region wins; a screen naming two is stating a preference it does not have. */
export function InitialFocus(v: boolean): El {
  return Prop("initialFocus", v);
}

/** NextFocus overrides where focus goes from here, per direction — {up,down,left,right} to node ids. It is an override, not the mechanism: a client works out the rest geometrically, and this is for the cases geometry gets wrong. */
export function NextFocus(v: Props): El {
  return Prop("nextFocus", v);
}

/** HasMore says this list is a page of something longer. It is the server's statement, not the client's inference: a page that happens to be full is not evidence there is another one, and a client guessing from the count asks for a page that does not exist. */
export function HasMore(v: boolean): El {
  return Prop("hasMore", v);
}

/** LoadMore is what fetches the next page. It carries whatever cursor the server needs, because only the server knows what 'next' means for this list — a skip count here, a token elsewhere. */
export function LoadMore(v: Action): El {
  return Prop("loadMore", v);
}

// ── bound sugar ────────────────────────────────────────────────────────────
// The same props, set to a binding the client resolves where the node renders.

/** BindOnTap sets "action" from the named path instead of from a value. */
export function BindOnTap(path: string): El {
  return Prop("action", bind(path));
}

/** BindFacetCount sets "count" from the named path instead of from a value. */
export function BindFacetCount(path: string): El {
  return Prop("count", bind(path));
}

/** BindTitle sets "title" from the named path instead of from a value. */
export function BindTitle(path: string): El {
  return Prop("title", bind(path));
}

/** BindSubtitle sets "subtitle" from the named path instead of from a value. */
export function BindSubtitle(path: string): El {
  return Prop("subtitle", bind(path));
}

/** BindPoster sets "poster" from the named path instead of from a value. */
export function BindPoster(path: string): El {
  return Prop("poster", bind(path));
}

/** BindBackdrop sets "backdrop" from the named path instead of from a value. */
export function BindBackdrop(path: string): El {
  return Prop("backdrop", bind(path));
}

/** BindLogo sets "logo" from the named path instead of from a value. */
export function BindLogo(path: string): El {
  return Prop("logo", bind(path));
}

/** BindOverview sets "overview" from the named path instead of from a value. */
export function BindOverview(path: string): El {
  return Prop("overview", bind(path));
}

/** BindMessage sets "message" from the named path instead of from a value. */
export function BindMessage(path: string): El {
  return Prop("message", bind(path));
}

/** BindProgress sets "progress" from the named path instead of from a value. */
export function BindProgress(path: string): El {
  return Prop("progress", bind(path));
}

/** BindBadgeText sets "badge" from the named path instead of from a value. */
export function BindBadgeText(path: string): El {
  return Prop("badge", bind(path));
}

/** BindActionLabel sets "actionLabel" from the named path instead of from a value. */
export function BindActionLabel(path: string): El {
  return Prop("actionLabel", bind(path));
}

/** BindMeta sets "meta" from the named path instead of from a value. */
export function BindMeta(path: string): El {
  return Prop("meta", bind(path));
}

/** BindGenres sets "genres" from the named path instead of from a value. */
export function BindGenres(path: string): El {
  return Prop("genres", bind(path));
}

/** BindResumeAt sets "resumeAt" from the named path instead of from a value. */
export function BindResumeAt(path: string): El {
  return Prop("resumeAt", bind(path));
}

/** BindMimeType sets "mimeType" from the named path instead of from a value. */
export function BindMimeType(path: string): El {
  return Prop("mimeType", bind(path));
}

/** BindNodeID sets "nodeId" from the named path instead of from a value. */
export function BindNodeID(path: string): El {
  return Prop("nodeId", bind(path));
}

/** BindPartID sets "partId" from the named path instead of from a value. */
export function BindPartID(path: string): El {
  return Prop("partId", bind(path));
}

/** BindDisabled sets "disabled" from the named path instead of from a value. */
export function BindDisabled(path: string): El {
  return Prop("disabled", bind(path));
}

/** BindIconName sets "icon" from the named path instead of from a value. */
export function BindIconName(path: string): El {
  return Prop("icon", bind(path));
}

/** BindItemWidth sets "itemWidth" from the named path instead of from a value. */
export function BindItemWidth(path: string): El {
  return Prop("itemWidth", bind(path));
}

/** BindGap sets "gap" from the named path instead of from a value. */
export function BindGap(path: string): El {
  return Prop("gap", bind(path));
}

/** BindMinColumnWidth sets "minColumnWidth" from the named path instead of from a value. */
export function BindMinColumnWidth(path: string): El {
  return Prop("minColumnWidth", bind(path));
}

/** BindRating sets "rating" from the named path instead of from a value. */
export function BindRating(path: string): El {
  return Prop("rating", bind(path));
}

/** BindRatingLabel sets "ratingLabel" from the named path instead of from a value. */
export function BindRatingLabel(path: string): El {
  return Prop("ratingLabel", bind(path));
}

/** BindYear sets "year" from the named path instead of from a value. */
export function BindYear(path: string): El {
  return Prop("year", bind(path));
}

/** BindIndex sets "index" from the named path instead of from a value. */
export function BindIndex(path: string): El {
  return Prop("index", bind(path));
}

/** BindRuntime sets "runtime" from the named path instead of from a value. */
export function BindRuntime(path: string): El {
  return Prop("runtime", bind(path));
}

/** BindThumbnail sets "thumbnail" from the named path instead of from a value. */
export function BindThumbnail(path: string): El {
  return Prop("thumbnail", bind(path));
}

/** BindWatched sets "watched" from the named path instead of from a value. */
export function BindWatched(path: string): El {
  return Prop("watched", bind(path));
}

/** BindCredits sets "credits" from the named path instead of from a value. */
export function BindCredits(path: string): El {
  return Prop("credits", bind(path));
}

/** BindQuality sets "quality" from the named path instead of from a value. */
export function BindQuality(path: string): El {
  return Prop("quality", bind(path));
}

/** BindLines sets "lines" from the named path instead of from a value. */
export function BindLines(path: string): El {
  return Prop("lines", bind(path));
}

/** BindCompact sets "compact" from the named path instead of from a value. */
export function BindCompact(path: string): El {
  return Prop("compact", bind(path));
}

/** BindPinAction sets "pinAction" from the named path instead of from a value. */
export function BindPinAction(path: string): El {
  return Prop("pinAction", bind(path));
}

/** BindKicker sets "kicker" from the named path instead of from a value. */
export function BindKicker(path: string): El {
  return Prop("kicker", bind(path));
}

/** BindNativeTitle sets "nativeTitle" from the named path instead of from a value. */
export function BindNativeTitle(path: string): El {
  return Prop("nativeTitle", bind(path));
}

/** BindProgressLabel sets "progressLabel" from the named path instead of from a value. */
export function BindProgressLabel(path: string): El {
  return Prop("progressLabel", bind(path));
}

/** BindShowTags sets "showTags" from the named path instead of from a value. */
export function BindShowTags(path: string): El {
  return Prop("showTags", bind(path));
}

/** BindOverlayTitle sets "overlayTitle" from the named path instead of from a value. */
export function BindOverlayTitle(path: string): El {
  return Prop("overlayTitle", bind(path));
}

/** BindAvatar sets "avatar" from the named path instead of from a value. */
export function BindAvatar(path: string): El {
  return Prop("avatar", bind(path));
}

/** BindRole sets "role" from the named path instead of from a value. */
export function BindRole(path: string): El {
  return Prop("role", bind(path));
}

/** BindAlign sets "align" from the named path instead of from a value. */
export function BindAlign(path: string): El {
  return Prop("align", bind(path));
}

/** BindJustify sets "justify" from the named path instead of from a value. */
export function BindJustify(path: string): El {
  return Prop("justify", bind(path));
}

/** BindWrap sets "wrap" from the named path instead of from a value. */
export function BindWrap(path: string): El {
  return Prop("wrap", bind(path));
}

/** BindRetry sets "retry" from the named path instead of from a value. */
export function BindRetry(path: string): El {
  return Prop("retry", bind(path));
}

/** BindShare sets "share" from the named path instead of from a value. */
export function BindShare(path: string): El {
  return Prop("share", bind(path));
}

/** BindDepth sets "depth" from the named path instead of from a value. */
export function BindDepth(path: string): El {
  return Prop("depth", bind(path));
}

/** BindBuckets sets "buckets" from the named path instead of from a value. */
export function BindBuckets(path: string): El {
  return Prop("buckets", bind(path));
}

/** BindStatusTone sets "tone" from the named path instead of from a value. */
export function BindStatusTone(path: string): El {
  return Prop("tone", bind(path));
}

/** BindRows sets "rows" from the named path instead of from a value. */
export function BindRows(path: string): El {
  return Prop("rows", bind(path));
}

/** BindSources sets "sources" from the named path instead of from a value. */
export function BindSources(path: string): El {
  return Prop("sources", bind(path));
}

/** BindOptions sets "options" from the named path instead of from a value. */
export function BindOptions(path: string): El {
  return Prop("options", bind(path));
}

/** BindCapabilities sets "capabilities" from the named path instead of from a value. */
export function BindCapabilities(path: string): El {
  return Prop("capabilities", bind(path));
}

/** BindSummary sets "summary" from the named path instead of from a value. */
export function BindSummary(path: string): El {
  return Prop("summary", bind(path));
}

/** BindValue sets "value" from the named path instead of from a value. */
export function BindValue(path: string): El {
  return Prop("value", bind(path));
}

/** BindPlaceholder sets "placeholder" from the named path instead of from a value. */
export function BindPlaceholder(path: string): El {
  return Prop("placeholder", bind(path));
}

/** BindHelp sets "help" from the named path instead of from a value. */
export function BindHelp(path: string): El {
  return Prop("help", bind(path));
}

/** BindInputType sets "inputType" from the named path instead of from a value. */
export function BindInputType(path: string): El {
  return Prop("inputType", bind(path));
}

/** BindValidators sets "validators" from the named path instead of from a value. */
export function BindValidators(path: string): El {
  return Prop("validators", bind(path));
}

/** BindVisibleWhen sets "visibleWhen" from the named path instead of from a value. */
export function BindVisibleWhen(path: string): El {
  return Prop("visibleWhen", bind(path));
}

/** BindFieldLabel sets "label" from the named path instead of from a value. */
export function BindFieldLabel(path: string): El {
  return Prop("label", bind(path));
}

/** BindChrome sets "chrome" from the named path instead of from a value. */
export function BindChrome(path: string): El {
  return Prop("chrome", bind(path));
}

/** BindBreadcrumb sets "breadcrumb" from the named path instead of from a value. */
export function BindBreadcrumb(path: string): El {
  return Prop("breadcrumb", bind(path));
}

/** BindLead sets "lead" from the named path instead of from a value. */
export function BindLead(path: string): El {
  return Prop("lead", bind(path));
}

/** BindHeading sets "heading" from the named path instead of from a value. */
export function BindHeading(path: string): El {
  return Prop("heading", bind(path));
}

/** BindSelected sets "selected" from the named path instead of from a value. */
export function BindSelected(path: string): El {
  return Prop("selected", bind(path));
}

/** BindIndent sets "indent" from the named path instead of from a value. */
export function BindIndent(path: string): El {
  return Prop("indent", bind(path));
}

/** BindActive sets "active" from the named path instead of from a value. */
export function BindActive(path: string): El {
  return Prop("active", bind(path));
}

/** BindHasPrev sets "hasPrev" from the named path instead of from a value. */
export function BindHasPrev(path: string): El {
  return Prop("hasPrev", bind(path));
}

/** BindHasNext sets "hasNext" from the named path instead of from a value. */
export function BindHasNext(path: string): El {
  return Prop("hasNext", bind(path));
}

/** BindPrevAction sets "prevAction" from the named path instead of from a value. */
export function BindPrevAction(path: string): El {
  return Prop("prevAction", bind(path));
}

/** BindNextAction sets "nextAction" from the named path instead of from a value. */
export function BindNextAction(path: string): El {
  return Prop("nextAction", bind(path));
}

/** BindOn sets "on" from the named path instead of from a value. */
export function BindOn(path: string): El {
  return Prop("on", bind(path));
}

/** BindOrigin sets "origin" from the named path instead of from a value. */
export function BindOrigin(path: string): El {
  return Prop("origin", bind(path));
}

/** BindVars sets "vars" from the named path instead of from a value. */
export function BindVars(path: string): El {
  return Prop("vars", bind(path));
}

/** BindName sets "name" from the named path instead of from a value. */
export function BindName(path: string): El {
  return Prop("name", bind(path));
}

/** BindSubmitAction sets "submitAction" from the named path instead of from a value. */
export function BindSubmitAction(path: string): El {
  return Prop("submitAction", bind(path));
}

/** BindSubmitLabel sets "submitLabel" from the named path instead of from a value. */
export function BindSubmitLabel(path: string): El {
  return Prop("submitLabel", bind(path));
}

/** BindBusy sets "busy" from the named path instead of from a value. */
export function BindBusy(path: string): El {
  return Prop("busy", bind(path));
}

/** BindError sets "error" from the named path instead of from a value. */
export function BindError(path: string): El {
  return Prop("error", bind(path));
}

/** BindOnAppear sets "onAppear" from the named path instead of from a value. */
export function BindOnAppear(path: string): El {
  return Prop("onAppear", bind(path));
}

/** BindOnDisappear sets "onDisappear" from the named path instead of from a value. */
export function BindOnDisappear(path: string): El {
  return Prop("onDisappear", bind(path));
}

/** BindA11yLabel sets "a11yLabel" from the named path instead of from a value. */
export function BindA11yLabel(path: string): El {
  return Prop("a11yLabel", bind(path));
}

/** BindHeadingLevel sets "headingLevel" from the named path instead of from a value. */
export function BindHeadingLevel(path: string): El {
  return Prop("headingLevel", bind(path));
}

/** BindLive sets "live" from the named path instead of from a value. */
export function BindLive(path: string): El {
  return Prop("live", bind(path));
}

/** BindFocusable sets "focusable" from the named path instead of from a value. */
export function BindFocusable(path: string): El {
  return Prop("focusable", bind(path));
}

/** BindFocusGroup sets "focusGroup" from the named path instead of from a value. */
export function BindFocusGroup(path: string): El {
  return Prop("focusGroup", bind(path));
}

/** BindInitialFocus sets "initialFocus" from the named path instead of from a value. */
export function BindInitialFocus(path: string): El {
  return Prop("initialFocus", bind(path));
}

/** BindNextFocus sets "nextFocus" from the named path instead of from a value. */
export function BindNextFocus(path: string): El {
  return Prop("nextFocus", bind(path));
}

/** BindHasMore sets "hasMore" from the named path instead of from a value. */
export function BindHasMore(path: string): El {
  return Prop("hasMore", bind(path));
}

/** BindLoadMore sets "loadMore" from the named path instead of from a value. */
export function BindLoadMore(path: string): El {
  return Prop("loadMore", bind(path));
}

// Tone values, mirroring the Go Tone constants. They are the schema enum's
// members rather than bare strings, so passing one where the contract wants a
// Tone typechecks.
export const ToneNeutral = Tone.Neutral;
export const ToneAccent = Tone.Accent;
export const ToneSuccess = Tone.Success;
export const ToneWarning = Tone.Warning;
export const ToneDanger = Tone.Danger;
export const ToneInfo = Tone.Info;

// ── actions ────────────────────────────────────────────────────────────────
// Actions ride inside the open props bag as JSON (ADR 0044); each constructor
// hides the discriminator and the optional fields.

/** Navigate pushes a screen, optionally with params. */
export function Navigate(screen: string, params?: Props): Action {
  return { kind: ActionKind.Navigate, screen, ...(params ? { params } : {}) };
}

/** Invoke runs a server mutation, optionally with input. */
export function Invoke(mutation: string, input?: Props): Action {
  return { kind: ActionKind.Invoke, mutation, ...(input ? { input } : {}) };
}

/** Play starts playback of a part. */
export function Play(partId: string): Action {
  return { kind: ActionKind.PlayPart, partId };
}

/** OpenURL opens an external URL (the client validates the scheme). */
export function OpenURL(url: string): Action {
  return { kind: ActionKind.OpenURL, url };
}

/** Back returns to the previous screen. */
export function Back(): Action {
  return { kind: ActionKind.Back };
}

/** Query re-reads a screen's data without changing the route. */
export function Query(screen: string, params?: Props): Action {
  return { kind: ActionKind.Query, screen, ...(params ? { params } : {}) };
}

/** OpenOverlay presents a node as a modal, sheet or drawer. */
export function OpenOverlay(surface: Surface): Action {
  return { kind: ActionKind.OpenOverlay, surface };
}

/** CloseOverlay dismisses the topmost overlay. */
export function CloseOverlay(): Action {
  return { kind: ActionKind.CloseOverlay };
}

/** Toast shows a transient message. */
export function Toast(message: string, tone?: Tone): Action {
  return { kind: ActionKind.Toast, message, ...(tone ? { tone } : {}) };
}

/** Sequence runs several actions in order, stopping at the first failure. */
export function Sequence(): Action {
  return { kind: ActionKind.Sequence };
}

/** SetValue writes a value into a named field in the enclosing form scope. */
export function SetValue(field: string, value: string): Action {
  return { kind: ActionKind.SetValue, field, value };
}

/** Submit runs an action with the enclosing State scope's values merged into its input. `field` names where they merge — a path into the input, or empty for its top level. */
export function Submit(): Action {
  return { kind: ActionKind.Submit };
}
