// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

/** One prop a primitive reads. */
export interface PropSpec {
  key: string;
  type: string;
  doc: string;
}

/** One native node type, with the reason it cannot be a definition. */
export interface PrimitiveSpec {
  type: string;
  tier: string;
  doc: string;
  native: string;
  children: boolean;
  props: PropSpec[];
}

/** The vocabulary version a client declares it implements. */
export const vocabularyVersion = "2.2.0";

/** Divides a module's id from its own type name; core types never contain it. */
export const typeSeparator = ":";

/** The single key that makes a prop value a binding rather than a literal. */
export const bindingMarker = "$bind";

/** The native tier — what a client must implement (ADR 0024). */
export const primitives: PrimitiveSpec[] = [
  {
    type: "Box",
    tier: "presentational",
    doc: "Box is the layout container every composition is built from.",
    native: "The irreducible layout leaf. A definition is a tree of primitives, so the base case cannot itself be a definition. It also resolves style.responsive against the live viewport, which is a render-time branch no static tree can carry.",
    children: true,
    props: [
      { key: "style", type: "boxStyle", doc: "Layout and surface style, including the responsive override." },
    ],
  },
  {
    type: "Text",
    tier: "presentational",
    doc: "Text renders a run of text in a token style. Children render after the text, for inline nesting.",
    native: "The irreducible text leaf.",
    children: true,
    props: [
      { key: "text", type: "string", doc: "The string to render." },
      { key: "style", type: "textStyle", doc: "Variant, weight and colour token." },
    ],
  },
  {
    type: "Image",
    tier: "presentational",
    doc: "Image renders a remote or proxied image with a placeholder fallback.",
    native: "Loading a resource, handling decode failure and falling back to a placeholder are client behaviours. It also feeds the art-light sampler, which reads decoded pixels.",
    children: false,
    props: [
      { key: "src", type: "string", doc: "Image URL. Platform-emitted URLs are artwork-proxy signed." },
      { key: "alt", type: "string", doc: "Alternative text." },
      { key: "fit", type: "enum:cover|contain", doc: "How the image fills its box." },
      { key: "placeholder", type: "string", doc: "Text shown while loading or when the source fails." },
      { key: "placeholderMode", type: "enum:label|initials", doc: "Whether the placeholder renders as a label or as initials." },
      { key: "artLight", type: "enum:ambient|focus", doc: "Publish this image's palette to the acrylic surfaces." },
      { key: "style", type: "boxStyle", doc: "Box style applied to the image frame." },
    ],
  },
  {
    type: "Icon",
    tier: "presentational",
    doc: "Icon renders one glyph from the client's bundled icon set.",
    native: "Resolves a name to a vector the client ships. The glyph set is a client asset, not data.",
    children: false,
    props: [
      { key: "name", type: "iconName", doc: "Icon name from the shared set." },
      { key: "size", type: "string|number", doc: "Rendered size; defaults to 1.2em." },
      { key: "color", type: "colorToken", doc: "Colour token override." },
    ],
  },
  {
    type: "Pressable",
    tier: "interactive",
    doc: "Pressable makes its subtree activate an Action.",
    native: "Turning a pointer, key or remote-control event into an Action dispatch is client behaviour.",
    children: true,
    props: [
      { key: "style", type: "boxStyle", doc: "Layout and surface style, including the responsive override." },
      { key: "action", type: "action", doc: "Action emitted on activation." },
      { key: "disabled", type: "boolean", doc: "Refuse activation and render the disabled state." },
      { key: "lift", type: "boolean", doc: "Apply the hover-lift affordance." },
      { key: "label", type: "string", doc: "Accessible label when the subtree carries no text." },
    ],
  },
  {
    type: "Spacer",
    tier: "presentational",
    doc: "Spacer occupies empty space in a stack, fixed or growing.",
    native: "An irreducible layout leaf.",
    children: false,
    props: [
      { key: "size", type: "spaceToken", doc: "Fixed size from the space scale." },
      { key: "grow", type: "boolean", doc: "Absorb the remaining free space instead." },
    ],
  },
  {
    type: "Fragment",
    tier: "presentational",
    doc: "Fragment renders its children with no wrapper of its own.",
    native: "A transparent grouping node the expander needs in order to return several nodes where one is expected.",
    children: true,
    props: [
    ],
  },
  {
    type: "Outlet",
    tier: "presentational",
    doc: "Outlet marks the point in a definition's template where the caller's slot content is substituted.",
    native: "It is the definition expander's own mechanism. A definition defined in terms of Outlet cannot itself be expanded without it, so it must be native.",
    children: true,
    props: [
      { key: "name", type: "string", doc: "Slot name filled from the caller's slots map." },
    ],
  },
  {
    type: "NavItem",
    tier: "interactive",
    doc: "NavItem is one entry in the app frame's navigation.",
    native: "Owns active-route state: it compares the current screen against its own target, which only the client knows.",
    children: false,
    props: [
      { key: "label", type: "string", doc: "Visible label." },
      { key: "icon", type: "iconName", doc: "Leading icon." },
      { key: "screen", type: "string", doc: "Screen this item marks as active." },
      { key: "action", type: "action", doc: "Action emitted on activation." },
    ],
  },
  {
    type: "NavBar",
    tier: "interactive",
    doc: "NavBar groups NavItems into the frame's responsive navigation.",
    native: "Presents as an inline bar or a bottom tab strip depending on the viewport — a render-time branch, not data.",
    children: true,
    props: [
    ],
  },
  {
    type: "Tabs",
    tier: "interactive",
    doc: "Tabs shows one panel at a time behind a tab strip. Each tab's content goes in the named slot matching its id, not in the ordered child list — an ordered child is dropped.",
    native: "Owns the active tab index.",
    children: false,
    props: [
      { key: "tabs", type: "array:tab", doc: "Tab descriptors, each an id and a label." },
    ],
  },
  {
    type: "Rotator",
    tier: "interactive",
    doc: "Rotator cross-fades through its children on a timer.",
    native: "Owns a timer and derives the active index from it, and republishes the active slide's palette to the acrylic surfaces.",
    children: true,
    props: [
      { key: "interval", type: "number", doc: "Dwell time per slide in milliseconds." },
    ],
  },
  {
    type: "State",
    tier: "interactive",
    doc: "State declares named variables and scopes them to its subtree. Children bind to them by name, and a setValue action writes them.",
    native: "It holds values across renders. A tree is a description of one moment; something has to remember what was typed between two of them, and no arrangement of static nodes can. It is also the scope boundary itself — which of two enclosing States a name resolves to is a question only the renderer, walking its own tree, can answer.",
    children: true,
    props: [
      { key: "vars", type: "array:stateVar", doc: "The variables this scope declares: each a name, a type (string, number or boolean) and an initial value. Declared rather than inferred so a client knows a name exists before anything writes to it, and knows what to coerce a written value to." },
    ],
  },
  {
    type: "TextInput",
    tier: "field",
    doc: "TextInput is a bare text entry field.",
    native: "Owns its input value between keystroke and submission.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "Field name under which an enclosing Form collects this value." },
      { key: "inputType", type: "string", doc: "Native input type — text, password, email, number." },
      { key: "placeholder", type: "string", doc: "Placeholder text." },
      { key: "value", type: "string", doc: "Initial value." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
      { key: "label", type: "string", doc: "Field label." },
    ],
  },
  {
    type: "Switch",
    tier: "field",
    doc: "Switch is a bare on/off control.",
    native: "Owns its on/off state.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "Field name under which an enclosing Form collects this value." },
      { key: "value", type: "boolean", doc: "Initial state." },
      { key: "action", type: "action", doc: "Action emitted on change, for a switch that acts immediately rather than being submitted." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
      { key: "label", type: "string", doc: "Field label." },
    ],
  },
  {
    type: "SelectInput",
    tier: "field",
    doc: "SelectInput is a bare dropdown.",
    native: "Owns its selected value.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "Field name under which an enclosing Form collects this value." },
      { key: "options", type: "array:option", doc: "Selectable options, each a value and a label." },
      { key: "value", type: "string", doc: "Initially selected value." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
      { key: "label", type: "string", doc: "Field label." },
    ],
  },
  {
    type: "SubmitField",
    tier: "field",
    doc: "SubmitField is a single text field with its own submit control.",
    native: "Owns its input value and substitutes it into the action at submit time.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "The field's name in the enclosing State scope. An input with a name writes what it holds there, which is what lets a screen carry more than one of them." },
      { key: "placeholder", type: "string", doc: "Placeholder text." },
      { key: "submitLabel", type: "string", doc: "Label of the submit control." },
      { key: "action", type: "action", doc: "Action emitted on submit, with the literal string \"$value\" replaced by the typed value wherever it appears." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
      { key: "label", type: "string", doc: "Field label." },
    ],
  },
  {
    type: "SearchBar",
    tier: "field",
    doc: "SearchBar is the frame's persistent search entry.",
    native: "The submitted action must carry the live input value, and in a live session the value streams up debounced as it changes.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "The field's name in the enclosing State scope. An input with a name writes what it holds there, which is what lets a screen carry more than one of them." },
      { key: "placeholder", type: "string", doc: "Placeholder text." },
      { key: "submitScreen", type: "string", doc: "Screen navigated to on submit when there is no live session." },
      { key: "value", type: "string", doc: "Initial term." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
      { key: "label", type: "string", doc: "Field label." },
    ],
  },
  {
    type: "Menu",
    tier: "interactive",
    doc: "Menu is a click-to-open list of actions behind a trigger.",
    native: "Owns its open/closed state.",
    children: false,
    props: [
      { key: "label", type: "string", doc: "Accessible label for the trigger." },
      { key: "initial", type: "string", doc: "Render an avatar-circle trigger showing this initial instead of the overflow glyph." },
      { key: "items", type: "array:menuItem", doc: "Menu entries, each a label with an optional icon, tone and action." },
    ],
  },
  {
    type: "Slider",
    tier: "field",
    doc: "Slider selects a number in a range.",
    native: "Displays its own live value beside itself, so output couples to internal state.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "Field name under which an enclosing Form collects this value." },
      { key: "label", type: "string", doc: "Field label, rendered beside the live value." },
      { key: "min", type: "number", doc: "Lower bound." },
      { key: "max", type: "number", doc: "Upper bound." },
      { key: "value", type: "number", doc: "Initial value." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
    ],
  },
  {
    type: "RatingControl",
    tier: "field",
    doc: "RatingControl selects a star rating.",
    native: "Owns the selection.",
    children: false,
    props: [
      { key: "name", type: "string", doc: "Field name under which an enclosing Form collects this value." },
      { key: "max", type: "number", doc: "Number of stars." },
      { key: "value", type: "number", doc: "Initial rating." },
      { key: "action", type: "action", doc: "Action emitted on change." },
      { key: "validators", type: "validators", doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot." },
      { key: "visibleWhen", type: "predicate", doc: "Structured predicate over sibling field values. Absent means always visible." },
      { key: "label", type: "string", doc: "Field label." },
    ],
  },
  {
    type: "SeasonSelector",
    tier: "interactive",
    doc: "SeasonSelector picks one season of a series.",
    native: "Owns the selected season.",
    children: false,
    props: [
      { key: "seasons", type: "array:season", doc: "Selectable seasons, each an id and a label with an optional action." },
      { key: "selected", type: "string", doc: "Initially selected season id." },
    ],
  },
  {
    type: "ProgressBar",
    tier: "computed",
    doc: "ProgressBar shows a linear completion fraction.",
    native: "Fill geometry is computed from the value at render.",
    children: false,
    props: [
      { key: "value", type: "number", doc: "Completion from 0 to 1." },
      { key: "tone", type: "tone", doc: "Fill tone." },
    ],
  },
  {
    type: "ProgressRing",
    tier: "computed",
    doc: "ProgressRing shows a circular completion fraction with the percentage inside.",
    native: "Arc geometry is computed from the value at render.",
    children: false,
    props: [
      { key: "value", type: "number", doc: "Completion from 0 to 1." },
      { key: "size", type: "number", doc: "Diameter in pixels." },
    ],
  },
  {
    type: "Skeleton",
    tier: "computed",
    doc: "Skeleton is an animated loading placeholder.",
    native: "Expands to a repeated animated shape; the animation is a client concern.",
    children: false,
    props: [
      { key: "shape", type: "enum:poster|line|block|circle", doc: "Placeholder shape." },
      { key: "count", type: "number", doc: "How many to render." },
    ],
  },
  {
    type: "Player",
    tier: "player",
    doc: "Player is the playback surface.",
    native: "The client owns the decoding pipeline and the transport controls (ADR 0047, ADR 0070). A scrub bar cannot be driven over a network at frame rate.",
    children: false,
    props: [
      { key: "src", type: "string", doc: "Playback URL issued by the Platform." },
      { key: "title", type: "string", doc: "Title shown in the player chrome." },
      { key: "poster", type: "string", doc: "Poster shown before the first frame." },
      { key: "mimeType", type: "string", doc: "Container MIME type." },
      { key: "resumeAt", type: "number", doc: "Seconds to seek to once the media is seekable." },
      { key: "nodeId", type: "string", doc: "Content node this playback reports progress against." },
      { key: "partId", type: "string", doc: "Release actually being played." },
    ],
  },
];

/** The definition tier — served as data, implemented by nobody. */
export const components: string[] = [
  "Screen",
  "Section",
  "Carousel",
  "Grid",
  "Stack",
  "HeroBanner",
  "PosterCard",
  "Button",
  "Badge",
  "Banner",
  "DetailHeader",
  "EpisodeRow",
  "PersonChip",
  "GenreTag",
  "EmptyState",
  "AppShell",
  "DetailHero",
  "Divider",
  "ErrorState",
  "ExtensionCard",
  "IconButton",
  "InfoPanel",
  "MediaTile",
  "Pagination",
  "PlaybackBar",
  "RelatedRail",
  "Select",
  "SettingsFrame",
  "SettingsNavGroup",
  "SettingsNavItem",
  "SourcePicker",
  "StatusIndicator",
  "TextField",
  "Toggle",
  "Form",
];

/** Every behaviour a client interprets. */
export const actionKinds: string[] = [
  "navigate",
  "invoke",
  "playPart",
  "openUrl",
  "back",
  "query",
  "openOverlay",
  "closeOverlay",
  "toast",
  "sequence",
  "setValue",
  "submit",
];

/** The closed accessible-role set. */
export const roles: string[] = [
  "alert",
  "button",
  "dialog",
  "group",
  "heading",
  "img",
  "link",
  "list",
  "listitem",
  "main",
  "navigation",
  "none",
  "progressbar",
  "region",
  "search",
  "status",
  "tab",
  "tablist",
  "tabpanel",
];

/** The closed field-validation set. */
export const validators: string[] = [
  "required",
  "minLength",
  "maxLength",
  "pattern",
  "matches",
  "oneOf",
];

/** The closed conditional set — no expression language, on purpose. */
export const predicates: string[] = [
  "equals",
  "notEmpty",
  "oneOf",
  "not",
  "all",
  "any",
];
