// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

// Package mosaic.session.v1 is the first-party client session transport
// (contracts#5): a typed, two-lane RPC surface generated from this one .proto into
// every client language. It supersedes the bespoke WebSocket of platform#22 and
// folds supervisor#4's live handover into stream resume.
//
// Two lanes, mapping onto the two gRPC shapes supported uniformly on every
// target client (web via Connect, Flutter, Compose, Swift):
//
//   - Lane 1 — intents (unary). Navigate, Invoke, SubmitInput, Attach. Each
//     resolves to the same application command/query the HTTP path would; the
//     command boundary (platform#12) and caller model (platform#13) are unchanged.
//   - Lane 2 — push (server-streaming). One long-lived Subscribe stream per
//     session over which the server pushes region updates, shell mutations,
//     toasts and unsolicited events. resume_cursor replays what a reconnecting
//     client missed.
//
// Deliberately no bidirectional streaming: unary + server-streaming are the one
// pair browsers support, so the wire stays uniform across all four clients.
//
// UINode subtrees ride the envelope as the typed mosaic.sdui.v1.UINode —
// contracts#6 (option (b) of contracts#5): the SDUI contract is protobuf, so the whole
// wire is typed end to end. Open bags that are genuinely screen- or
// action-specific (params, input, event payloads) still ride as JSON bytes.

// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=none"
// @generated from file mosaic/session/v1/session.proto (package mosaic.session.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { UINode } from "../../sdui/v1/sdui_pb";
import { file_mosaic_sdui_v1_sdui } from "../../sdui/v1/sdui_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mosaic/session/v1/session.proto.
 */
export const file_mosaic_session_v1_session: GenFile = /*@__PURE__*/
  fileDesc("Ch9tb3NhaWMvc2Vzc2lvbi92MS9zZXNzaW9uLnByb3RvEhFtb3NhaWMuc2Vzc2lvbi52MSIFCgNBY2sirQEKDUF0dGFjaFJlcXVlc3QSDwoHc2Vzc2lvbhgBIAEoCRIOCgZzY3JlZW4YAiABKAkSDgoGcGFyYW1zGAMgASgMEjEKB3Byb2ZpbGUYBCABKAsyIC5tb3NhaWMuc2Vzc2lvbi52MS5DbGllbnRQcm9maWxlEjgKCnZvY2FidWxhcnkYBSABKAsyJC5tb3NhaWMuc2Vzc2lvbi52MS5Wb2NhYnVsYXJ5UHJvZmlsZSJJChFWb2NhYnVsYXJ5UHJvZmlsZRIPCgd2ZXJzaW9uGAEgASgJEhIKCnByaW1pdGl2ZXMYAiADKAkSDwoHYWN0aW9ucxgDIAMoCSJwCg1DbGllbnRQcm9maWxlEhIKCmNvbnRhaW5lcnMYASADKAkSFAoMdmlkZW9fY29kZWNzGAIgAygJEhQKDGF1ZGlvX2NvZGVjcxgDIAMoCRILCgNoZHIYBCABKAgSEgoKbWF4X2hlaWdodBgFIAEoBSJCCg9OYXZpZ2F0ZVJlcXVlc3QSDwoHc2Vzc2lvbhgBIAEoCRIOCgZzY3JlZW4YAiABKAkSDgoGcGFyYW1zGAMgASgMIj8KDUludm9rZVJlcXVlc3QSDwoHc2Vzc2lvbhgBIAEoCRIOCgZhY3Rpb24YAiABKAkSDQoFaW5wdXQYAyABKAwiLgoMSW5wdXRSZXF1ZXN0Eg8KB3Nlc3Npb24YASABKAkSDQoFdmFsdWUYAiABKAkiOgoQU3Vic2NyaWJlUmVxdWVzdBIPCgdzZXNzaW9uGAEgASgJEhUKDXJlc3VtZV9jdXJzb3IYAiABKAQilgIKDVNlcnZlck1lc3NhZ2USCwoDc2VxGAEgASgEEjEKBnJlZ2lvbhgCIAEoCzIfLm1vc2FpYy5zZXNzaW9uLnYxLlJlZ2lvblVwZGF0ZUgAEi8KBXNoZWxsGAMgASgLMh4ubW9zYWljLnNlc3Npb24udjEuU2hlbGxVcGRhdGVIABIpCgV0b2FzdBgEIAEoCzIYLm1vc2FpYy5zZXNzaW9uLnYxLlRvYXN0SAASKQoFZXZlbnQYBSABKAsyGC5tb3NhaWMuc2Vzc2lvbi52MS5FdmVudEgAEjYKDGZpZWxkX2Vycm9ycxgGIAEoCzIeLm1vc2FpYy5zZXNzaW9uLnYxLkZpZWxkRXJyb3JzSABCBgoEYm9keSJQCgtGaWVsZEVycm9ycxItCgZlcnJvcnMYASADKAsyHS5tb3NhaWMuc2Vzc2lvbi52MS5GaWVsZEVycm9yEhIKCmZvcm1fZXJyb3IYAiABKAkiLAoKRmllbGRFcnJvchINCgVmaWVsZBgBIAEoCRIPCgdtZXNzYWdlGAIgASgJIroBCgxSZWdpb25VcGRhdGUSDgoGcmVnaW9uGAEgASgJEi4KAm9wGAIgASgOMiIubW9zYWljLnNlc3Npb24udjEuUmVnaW9uVXBkYXRlLk9wEicKB3VpX25vZGUYAyABKAsyFi5tb3NhaWMuc2R1aS52MS5VSU5vZGUiQQoCT3ASCwoHUkVQTEFDRRAAEgoKBkFQUEVORBABEgsKB1BSRVBFTkQQAhIKCgZSRU1PVkUQAxIJCgVQQVRDSBAEIjYKC1NoZWxsVXBkYXRlEicKB3VpX25vZGUYASABKAsyFi5tb3NhaWMuc2R1aS52MS5VSU5vZGUiVwoFVG9hc3QSDwoHbWVzc2FnZRgBIAEoCRIMCgR0b25lGAIgASgJEgoKAmlkGAMgASgJEhIKCnBlcnNpc3RlbnQYBCABKAgSDwoHY2xlYXJlZBgFIAEoCCImCgVFdmVudBIMCgR0eXBlGAEgASgJEg8KB3BheWxvYWQYAiABKAwy/gIKDlNlc3Npb25TZXJ2aWNlEkIKBkF0dGFjaBIgLm1vc2FpYy5zZXNzaW9uLnYxLkF0dGFjaFJlcXVlc3QaFi5tb3NhaWMuc2Vzc2lvbi52MS5BY2sSRgoITmF2aWdhdGUSIi5tb3NhaWMuc2Vzc2lvbi52MS5OYXZpZ2F0ZVJlcXVlc3QaFi5tb3NhaWMuc2Vzc2lvbi52MS5BY2sSQgoGSW52b2tlEiAubW9zYWljLnNlc3Npb24udjEuSW52b2tlUmVxdWVzdBoWLm1vc2FpYy5zZXNzaW9uLnYxLkFjaxJGCgtTdWJtaXRJbnB1dBIfLm1vc2FpYy5zZXNzaW9uLnYxLklucHV0UmVxdWVzdBoWLm1vc2FpYy5zZXNzaW9uLnYxLkFjaxJUCglTdWJzY3JpYmUSIy5tb3NhaWMuc2Vzc2lvbi52MS5TdWJzY3JpYmVSZXF1ZXN0GiAubW9zYWljLnNlc3Npb24udjEuU2VydmVyTWVzc2FnZTABQkNaQWdpdGh1Yi5jb20vbW9zYWljLW1lZGlhL2NvbnRyYWN0cy9nZW4vbW9zYWljL3Nlc3Npb24vdjE7c2Vzc2lvbnYxYgZwcm90bzM", [file_mosaic_sdui_v1_sdui]);

/**
 * Ack is the empty reply to an intent. An intent either succeeds (Ack) or fails
 * with a Connect/gRPC error carrying a Platform error category; its visible
 * effect arrives on the push lane, not in this reply.
 *
 * @generated from message mosaic.session.v1.Ack
 */
export type Ack = Message<"mosaic.session.v1.Ack"> & {
};

/**
 * Describes the message mosaic.session.v1.Ack.
 * Use `create(AckSchema)` to create a new message.
 */
export const AckSchema: GenMessage<Ack> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 0);

/**
 * AttachRequest binds a session and optionally declares the route to show.
 *
 * @generated from message mosaic.session.v1.AttachRequest
 */
export type AttachRequest = Message<"mosaic.session.v1.AttachRequest"> & {
  /**
   * The caller's opaque credential (platform#13), which is its **access token**
   * since platform#58 made the session a bearer pair. The field keeps its name
   * because every client sends it in the same place and for the same reason;
   * what changed is that the value is minutes-lived and rotates, so a client
   * that caches it forever will start seeing UNAUTHENTICATED and must refresh
   * rather than re-authenticate.
   *
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * optional route to (re-)assert; empty leaves it unchanged.
   *
   * @generated from field: string screen = 2;
   */
  screen: string;

  /**
   * optional screen params as a JSON object (see params note).
   *
   * @generated from field: bytes params = 3;
   */
  params: Uint8Array;

  /**
   * What this client can actually play (web#4). Optional: a client that
   * declares nothing gets whatever the server assumes, which is what every
   * client got before this field existed.
   *
   * @generated from field: mosaic.session.v1.ClientProfile profile = 4;
   */
  profile?: ClientProfile | undefined;

  /**
   * What this client can *render* — the other half of the same question
   * `profile` answers about decoding. Optional, and an absent one is not an
   * error: a client built against an older contract is assumed to implement the
   * whole vocabulary, which is exactly what every client was assumed to do
   * before this field existed.
   *
   * @generated from field: mosaic.session.v1.VocabularyProfile vocabulary = 5;
   */
  vocabulary?: VocabularyProfile | undefined;
};

/**
 * Describes the message mosaic.session.v1.AttachRequest.
 * Use `create(AttachRequestSchema)` to create a new message.
 */
export const AttachRequestSchema: GenMessage<AttachRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 1);

/**
 * VocabularyProfile is the SDUI vocabulary a client implements, declared once
 * per connection.
 *
 * It exists because the server was emitting into the dark. The vocabulary is
 * versioned and grows, clients are released on their own schedules, and until
 * this field existed nothing carried the answer to "can the thing I am about to
 * send actually be drawn?" — so an unsupported node became a placeholder on the
 * client and nothing anywhere recorded it. That is the same failure as a prop
 * nobody reads: visible only if someone happens to be looking at that screen.
 *
 * The client is the only thing that knows, and it knows mechanically: the
 * primitives are the types it registers and the actions are the kinds its
 * dispatcher interprets. Both are published as data in
 * conformance/vocabulary.json, so a client can state its answer against the
 * contract rather than against a list somebody maintains.
 *
 * Components are deliberately absent. They are definitions the server delivers
 * (contracts#4), so a client renders whatever it is sent; what it can fail to draw
 * is a *primitive* inside a definition's template, which is what
 * ComponentDefinition.fallback answers.
 *
 * @generated from message mosaic.session.v1.VocabularyProfile
 */
export type VocabularyProfile = Message<"mosaic.session.v1.VocabularyProfile"> & {
  /**
   * The vocabulary version this client implements, e.g. "1.0.0". Empty when the
   * client does not know its own version, which is treated as an undeclared
   * vocabulary rather than as version zero.
   *
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * Native node types it renders. A type the server would emit that is not here
   * is not sent.
   *
   * @generated from field: repeated string primitives = 2;
   */
  primitives: string[];

  /**
   * Action kinds its dispatcher interprets. An action of any other kind is
   * stripped before the node is sent, because a control wired to a kind the
   * client ignores is a control that does nothing when pressed.
   *
   * @generated from field: repeated string actions = 3;
   */
  actions: string[];
};

/**
 * Describes the message mosaic.session.v1.VocabularyProfile.
 * Use `create(VocabularyProfileSchema)` to create a new message.
 */
export const VocabularyProfileSchema: GenMessage<VocabularyProfile> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 2);

/**
 * ClientProfile is what a client can decode, declared once per connection.
 *
 * It exists because the server was guessing. Stream selection (platform#27) ranks a
 * source's candidates against what the caller can play, and with no declaration
 * the Platform hard-coded a desktop browser's abilities at the call site —
 * honest for one client and a lie for the four the transport was built to serve
 * (contracts#5).
 *
 * The client is the only thing that knows. A browser can answer precisely via
 * canPlayType (web#5); a native player knows its own decoders. Neither is
 * something a server can infer from a user agent without being wrong eventually.
 *
 * It is also what the resolution cache is keyed on (platform#28): the Platform
 * reduces this to a stable class, so clients that decode the same things share
 * one cached resolution rather than each paying for their own.
 *
 * @generated from message mosaic.session.v1.ClientProfile
 */
export type ClientProfile = Message<"mosaic.session.v1.ClientProfile"> & {
  /**
   * Containers, video and audio codecs the client can decode, as the names
   * ffprobe uses ("matroska", "hevc", "eac3") so a declaration and a probe are
   * directly comparable rather than two vocabularies.
   *
   * @generated from field: repeated string containers = 1;
   */
  containers: string[];

  /**
   * @generated from field: repeated string video_codecs = 2;
   */
  videoCodecs: string[];

  /**
   * @generated from field: repeated string audio_codecs = 3;
   */
  audioCodecs: string[];

  /**
   * Whether the client can *render* high dynamic range, which is a separate
   * question from decoding the codec that carries it: an SDR display given
   * HDR10 renders it wrong rather than not at all.
   *
   * @generated from field: bool hdr = 4;
   */
  hdr: boolean;

  /**
   * Largest useful height, 0 for uncapped. A phone gains nothing from pixels it
   * cannot show and pays for them in bandwidth.
   *
   * @generated from field: int32 max_height = 5;
   */
  maxHeight: number;
};

/**
 * Describes the message mosaic.session.v1.ClientProfile.
 * Use `create(ClientProfileSchema)` to create a new message.
 */
export const ClientProfileSchema: GenMessage<ClientProfile> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 3);

/**
 * NavigateRequest opens a screen.
 *
 * @generated from message mosaic.session.v1.NavigateRequest
 */
export type NavigateRequest = Message<"mosaic.session.v1.NavigateRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: string screen = 2;
   */
  screen: string;

  /**
   * screen params as a JSON object (see params note).
   *
   * @generated from field: bytes params = 3;
   */
  params: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.NavigateRequest.
 * Use `create(NavigateRequestSchema)` to create a new message.
 */
export const NavigateRequestSchema: GenMessage<NavigateRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 4);

/**
 * InvokeRequest runs a named action. input is the action's argument envelope in
 * the SDUI runtime's JSON shape (platform#19), carried opaquely and decoded by the
 * action's Platform handler.
 *
 * @generated from message mosaic.session.v1.InvokeRequest
 */
export type InvokeRequest = Message<"mosaic.session.v1.InvokeRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * the action/mutation name, e.g. "importContent".
   *
   * @generated from field: string action = 2;
   */
  action: string;

  /**
   * JSON argument envelope.
   *
   * @generated from field: bytes input = 3;
   */
  input: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.InvokeRequest.
 * Use `create(InvokeRequestSchema)` to create a new message.
 */
export const InvokeRequestSchema: GenMessage<InvokeRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 5);

/**
 * InputRequest carries one search-as-you-type value.
 *
 * @generated from message mosaic.session.v1.InputRequest
 */
export type InputRequest = Message<"mosaic.session.v1.InputRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message mosaic.session.v1.InputRequest.
 * Use `create(InputRequestSchema)` to create a new message.
 */
export const InputRequestSchema: GenMessage<InputRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 6);

/**
 * SubscribeRequest opens the push lane. resume_cursor is the last
 * ServerMessage.seq the client saw; 0 on a fresh connect.
 *
 * @generated from message mosaic.session.v1.SubscribeRequest
 */
export type SubscribeRequest = Message<"mosaic.session.v1.SubscribeRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;

  /**
   * @generated from field: uint64 resume_cursor = 2;
   */
  resumeCursor: bigint;
};

/**
 * Describes the message mosaic.session.v1.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 7);

/**
 * ServerMessage is one push. seq is monotonic per session and is the resume
 * cursor a reconnecting client presents.
 *
 * A note on params/input as JSON bytes: screen params and action inputs are an
 * open, screen- and action-specific bag (a content ref, a season number, a
 * search string), so they ride as a JSON object rather than a fixed message —
 * the typed envelope carries an open payload where the payload is genuinely
 * open, while the UI tree itself is the typed mosaic.sdui.v1.UINode.
 *
 * @generated from message mosaic.session.v1.ServerMessage
 */
export type ServerMessage = Message<"mosaic.session.v1.ServerMessage"> & {
  /**
   * @generated from field: uint64 seq = 1;
   */
  seq: bigint;

  /**
   * @generated from oneof mosaic.session.v1.ServerMessage.body
   */
  body: {
    /**
     * a named region changed.
     *
     * @generated from field: mosaic.session.v1.RegionUpdate region = 2;
     */
    value: RegionUpdate;
    case: "region";
  } | {
    /**
     * the app shell (re)rendered.
     *
     * @generated from field: mosaic.session.v1.ShellUpdate shell = 3;
     */
    value: ShellUpdate;
    case: "shell";
  } | {
    /**
     * a transient notice.
     *
     * @generated from field: mosaic.session.v1.Toast toast = 4;
     */
    value: Toast;
    case: "toast";
  } | {
    /**
     * an unsolicited domain event.
     *
     * @generated from field: mosaic.session.v1.Event event = 5;
     */
    value: Event;
    case: "event";
  } | {
    /**
     * a submission was rejected, per field.
     *
     * @generated from field: mosaic.session.v1.FieldErrors field_errors = 6;
     */
    value: FieldErrors;
    case: "fieldErrors";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message mosaic.session.v1.ServerMessage.
 * Use `create(ServerMessageSchema)` to create a new message.
 */
export const ServerMessageSchema: GenMessage<ServerMessage> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 8);

/**
 * FieldErrors carries a rejected submission back to the fields that caused it.
 *
 * It exists because client-side validation and server-side rejection are the
 * same statement made twice, and only one of them had anywhere to land. A client
 * enforces the six validators the contract declares; a server enforces
 * everything a client cannot know — that a username is taken, that a key is
 * invalid — and until now the only way it could say so was a toast, which is a
 * sentence about a form floating next to it rather than a mark on the field that
 * is wrong.
 *
 * Symmetric on purpose: this is the shape a client already produces locally, so
 * a rejection from either side renders identically and a screen cannot tell you
 * where the problem is in two different ways.
 *
 * @generated from message mosaic.session.v1.FieldErrors
 */
export type FieldErrors = Message<"mosaic.session.v1.FieldErrors"> & {
  /**
   * @generated from field: repeated mosaic.session.v1.FieldError errors = 1;
   */
  errors: FieldError[];

  /**
   * A failure that belongs to the submission rather than to any one field — a
   * conflict between two of them, or a service that was unavailable.
   *
   * @generated from field: string form_error = 2;
   */
  formError: string;
};

/**
 * Describes the message mosaic.session.v1.FieldErrors.
 * Use `create(FieldErrorsSchema)` to create a new message.
 */
export const FieldErrorsSchema: GenMessage<FieldErrors> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 9);

/**
 * FieldError names the field and what is wrong with it.
 *
 * @generated from message mosaic.session.v1.FieldError
 */
export type FieldError = Message<"mosaic.session.v1.FieldError"> & {
  /**
   * The field's name in the enclosing State scope, which is what the input that
   * wrote it declares. A name matching no field renders as a form-level error
   * rather than being dropped: a rejection nobody can see is worse than one in
   * the wrong place.
   *
   * @generated from field: string field = 1;
   */
  field: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message mosaic.session.v1.FieldError.
 * Use `create(FieldErrorSchema)` to create a new message.
 */
export const FieldErrorSchema: GenMessage<FieldError> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 10);

/**
 * RegionUpdate applies one operation to a named region (platform#19 / 0031). The
 * op-set is contract-owned and transport-agnostic: a Compose composable, a
 * SwiftUI view and a React component apply the same ops.
 *
 * @generated from message mosaic.session.v1.RegionUpdate
 */
export type RegionUpdate = Message<"mosaic.session.v1.RegionUpdate"> & {
  /**
   * a named slot (platform#19 / 0031), e.g. "content".
   *
   * @generated from field: string region = 1;
   */
  region: string;

  /**
   * @generated from field: mosaic.session.v1.RegionUpdate.Op op = 2;
   */
  op: RegionUpdate_Op;

  /**
   * the typed UINode subtree (contracts#6).
   *
   * @generated from field: mosaic.sdui.v1.UINode ui_node = 3;
   */
  uiNode?: UINode | undefined;
};

/**
 * Describes the message mosaic.session.v1.RegionUpdate.
 * Use `create(RegionUpdateSchema)` to create a new message.
 */
export const RegionUpdateSchema: GenMessage<RegionUpdate> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 11);

/**
 * Op is the region operation. REPLACE is the whole-region default; the
 * narrower ops let a producer target part of a region without resending it.
 *
 * @generated from enum mosaic.session.v1.RegionUpdate.Op
 */
export enum RegionUpdate_Op {
  /**
   * @generated from enum value: REPLACE = 0;
   */
  REPLACE = 0,

  /**
   * @generated from enum value: APPEND = 1;
   */
  APPEND = 1,

  /**
   * @generated from enum value: PREPEND = 2;
   */
  PREPEND = 2,

  /**
   * @generated from enum value: REMOVE = 3;
   */
  REMOVE = 3,

  /**
   * @generated from enum value: PATCH = 4;
   */
  PATCH = 4,
}

/**
 * Describes the enum mosaic.session.v1.RegionUpdate.Op.
 */
export const RegionUpdate_OpSchema: GenEnum<RegionUpdate_Op> = /*@__PURE__*/
  enumDesc(file_mosaic_session_v1_session, 11, 0);

/**
 * ShellUpdate carries the app shell UINode tree (platform#21). It is sent once on
 * connect and again only if the shell itself changes.
 *
 * @generated from message mosaic.session.v1.ShellUpdate
 */
export type ShellUpdate = Message<"mosaic.session.v1.ShellUpdate"> & {
  /**
   * the typed shell UINode tree (contracts#6).
   *
   * @generated from field: mosaic.sdui.v1.UINode ui_node = 1;
   */
  uiNode?: UINode | undefined;
};

/**
 * Describes the message mosaic.session.v1.ShellUpdate.
 * Use `create(ShellUpdateSchema)` to create a new message.
 */
export const ShellUpdateSchema: GenMessage<ShellUpdate> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 12);

/**
 * Toast is one message in the client's notification stack, in one of two
 * lifetimes (platform#30).
 *
 * A **toast** is transient: the confirmation an Invoke pushes, which removes
 * itself on a timer. That is right for "import finished" and wrong for a
 * condition still true a minute later — a transient message for a lasting
 * condition is announced once and is then invisible to anybody who looked away.
 *
 * A **notice** is the same surface with the other lifetime: it stays until the
 * user dismisses it or the server retracts it. One surface and two lifetimes
 * rather than two surfaces, deliberately — giving a lasting condition its own
 * region would put two competing places to look for "something is wrong", and
 * the one that appears less often is the one people stop checking.
 *
 * A notice is therefore *identified*, which a toast never needed to be: a
 * fire-and-forget message removes itself, but one the server must later update
 * or retract has to be nameable.
 *
 * @generated from message mosaic.session.v1.Toast
 */
export type Toast = Message<"mosaic.session.v1.Toast"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * "success" | "danger" | "info" — an SDUI tone.
   *
   * @generated from field: string tone = 2;
   */
  tone: string;

  /**
   * id names a standing notice, so a repeat of the same condition updates the
   * notice already showing rather than stacking a fifth copy of it, and so a
   * recovery can retract the exact one it fixed. Empty is an anonymous
   * transient toast, which needs no name because it removes itself.
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * persistent holds this message until it is dismissed or retracted, instead
   * of expiring on the client's timer. It requires id: a message the client
   * will keep indefinitely and the server can never name again is a permanent
   * one.
   *
   * @generated from field: bool persistent = 4;
   */
  persistent: boolean;

  /**
   * cleared retracts the notice named by id — the condition resolved. message
   * and tone are ignored. A client that holds no such notice ignores it, which
   * is the ordinary case after a reconnect rebuilt the stack from nothing.
   *
   * @generated from field: bool cleared = 5;
   */
  cleared: boolean;
};

/**
 * Describes the message mosaic.session.v1.Toast.
 * Use `create(ToastSchema)` to create a new message.
 */
export const ToastSchema: GenMessage<Toast> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 13);

/**
 * Event is an unsolicited domain event: an import finished, a config changed, a
 * library edit from another device. This is the channel request/response cannot
 * provide and the reason a live lane exists at all.
 *
 * @generated from message mosaic.session.v1.Event
 */
export type Event = Message<"mosaic.session.v1.Event"> & {
  /**
   * event type name.
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * event-specific JSON payload.
   *
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * Describes the message mosaic.session.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_mosaic_session_v1_session, 14);

/**
 * SessionService is the live client session. Intents are unary; push is one
 * server-streaming call. Over HTTP/2 both lanes multiplex onto a single
 * connection, so the two-lane logical split costs one physical connection.
 *
 * @generated from service mosaic.session.v1.SessionService
 */
export const SessionService: GenService<{
  /**
   * Attach (re)binds this caller to a session and declares the route it wants
   * shown. A reconnecting client calls it to re-assert the exact screen that
   * was open, the same re-declaration the platform#22 socket did on reconnect.
   *
   * @generated from rpc mosaic.session.v1.SessionService.Attach
   */
  attach: {
    methodKind: "unary";
    input: typeof AttachRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * Navigate opens a screen; the server renders it into the content region on
   * the push lane.
   *
   * @generated from rpc mosaic.session.v1.SessionService.Navigate
   */
  navigate: {
    methodKind: "unary";
    input: typeof NavigateRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * Invoke runs a named action (an SDUI Action, platform#19) — a mutation — and
   * pushes a toast plus a re-render of the current content.
   *
   * @generated from rpc mosaic.session.v1.SessionService.Invoke
   */
  invoke: {
    methodKind: "unary";
    input: typeof InvokeRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * SubmitInput carries one search-as-you-type keystroke. The Platform
   * debounces these against session state before sourcing, so a fast typist
   * does not fan out a request per keystroke to the upstream addons.
   *
   * @generated from rpc mosaic.session.v1.SessionService.SubmitInput
   */
  submitInput: {
    methodKind: "unary";
    input: typeof InputRequestSchema;
    output: typeof AckSchema;
  },
  /**
   * Subscribe opens the push lane: one long-lived server-stream per session.
   * resume_cursor replays what a reconnecting client missed (superseding
   * supervisor#4's handover).
   *
   * @generated from rpc mosaic.session.v1.SessionService.Subscribe
   */
  subscribe: {
    methodKind: "server_streaming";
    input: typeof SubscribeRequestSchema;
    output: typeof ServerMessageSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_mosaic_session_v1_session, 0);

