#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors
/*
 * Generate tokens/tokens.css from tokens/tokens.json — the design tokens as CSS
 * custom properties, for a web client.
 *
 * The JSON is the authored source and the Platform serves it (definitions.go's
 * neighbour, tokens.Set()), so a running client can be re-skinned without a
 * release. This sheet is the same values in the form a browser can apply before
 * the session connects: it is a BOOTSTRAP, not a second source. If the two ever
 * disagree, the JSON is right and this file was not regenerated.
 *
 * What is NOT here: anything that derives from a token — a colour mixed from the
 * accent, a gradient composed of two tokens, the acrylic material's layers.
 * Those are formulas, and a formula belongs to the client that evaluates it
 * (sdui-react's skin.css), not to the contract.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const doc = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));

const emit = (group) =>
  Object.entries(group)
    .map(([name, tok]) => `  --${name}: ${tok.$value};`)
    .join("\n");

const css = `/* Code generated by scripts/gen-tokens.mjs from tokens/tokens.json. DO NOT EDIT. */
/* SPDX-License-Identifier: Apache-2.0 */
/* SPDX-FileCopyrightText: 2026 the Mosaic authors */

/*
 * The design tokens as CSS custom properties — the bootstrap copy a web client
 * applies before the Platform has sent anything. The Platform serves the same
 * set over the session and a client overrides these at runtime, so a re-skin
 * needs no client release.
 *
 * Derived values (color-mix, gradients over tokens, the acrylic layers) are not
 * here: they are formulas the client evaluates over these values.
 */

:root,
:root[data-theme="dark"] {
${emit(doc.themes.dark)}
}

:root[data-theme="light"] {
${emit(doc.themes.light)}
}

:root {
${emit(doc.base)}
}
`;

writeFileSync(join(root, "tokens/tokens.css"), css);
const n = Object.keys(doc.base).length + Object.keys(doc.themes.dark).length + Object.keys(doc.themes.light).length;
console.log(`wrote tokens/tokens.css (${n} tokens)`);
