// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

package ui

import "github.com/mosaic-media/contracts/sdui"

// ── primitives ─────────────────────────────────────────────────────────────
// The native tier: node types a client implements itself. They are authored
// here rather than through Component("Box", …) because a type spelled as a
// string is a type nothing checks — which is how seven primitives came to be
// emitted by name with no entry in any contract.

// Box is the layout container every composition is built from.
// Native: The irreducible layout leaf. A definition is a tree of primitives, so the base case cannot itself be a definition. It also resolves style.responsive against the live viewport, which is a render-time branch no static tree can carry.
func Box(els ...El) *Element { return compose("Box", nil, els) }

// Text renders a run of text in a token style. Children render after the text, for inline nesting.
// Native: The irreducible text leaf.
func Text(els ...El) *Element { return compose("Text", nil, els) }

// Image renders a remote or proxied image with a placeholder fallback.
// Native: Loading a resource, handling decode failure and falling back to a placeholder are client behaviours. It also feeds the art-light sampler, which reads decoded pixels.
func Image(els ...El) *Element { return compose("Image", nil, els) }

// Icon renders one glyph from the client's bundled icon set.
// Native: Resolves a name to a vector the client ships. The glyph set is a client asset, not data.
func Icon(els ...El) *Element { return compose("Icon", nil, els) }

// Pressable makes its subtree activate an Action.
// Native: Turning a pointer, key or remote-control event into an Action dispatch is client behaviour.
func Pressable(els ...El) *Element { return compose("Pressable", nil, els) }

// Spacer occupies empty space in a stack, fixed or growing.
// Native: An irreducible layout leaf.
func Spacer(els ...El) *Element { return compose("Spacer", nil, els) }

// Fragment renders its children with no wrapper of its own.
// Native: A transparent grouping node the expander needs in order to return several nodes where one is expected.
func Fragment(els ...El) *Element { return compose("Fragment", nil, els) }

// Outlet marks the point in a definition's template where the caller's slot content is substituted.
// Native: It is the definition expander's own mechanism. A definition defined in terms of Outlet cannot itself be expanded without it, so it must be native.
func Outlet(els ...El) *Element { return compose("Outlet", nil, els) }

// NavItem is one entry in the app frame's navigation.
// Native: Owns active-route state: it compares the current screen against its own target, which only the client knows.
func NavItem(els ...El) *Element { return compose("NavItem", nil, els) }

// NavBar groups NavItems into the frame's responsive navigation.
// Native: Presents as an inline bar or a bottom tab strip depending on the viewport — a render-time branch, not data.
func NavBar(els ...El) *Element { return compose("NavBar", nil, els) }

// Tabs shows one panel at a time behind a tab strip. Each tab's content goes in the named slot matching its id, not in the ordered child list — an ordered child is dropped.
// Native: Owns the active tab index.
func Tabs(els ...El) *Element { return compose("Tabs", nil, els) }

// Rotator cross-fades through its children on a timer.
// Native: Owns a timer and derives the active index from it, and republishes the active slide's palette to the acrylic surfaces.
func Rotator(els ...El) *Element { return compose("Rotator", nil, els) }

// State declares named variables and scopes them to its subtree. Children bind to them by name, and a setValue action writes them.
// Native: It holds values across renders. A tree is a description of one moment; something has to remember what was typed between two of them, and no arrangement of static nodes can. It is also the scope boundary itself — which of two enclosing States a name resolves to is a question only the renderer, walking its own tree, can answer.
func State(els ...El) *Element { return compose("State", nil, els) }

// TextInput is a bare text entry field.
// Native: Owns its input value between keystroke and submission.
func TextInput(els ...El) *Element { return compose("TextInput", nil, els) }

// Switch is a bare on/off control.
// Native: Owns its on/off state.
func Switch(els ...El) *Element { return compose("Switch", nil, els) }

// SelectInput is a bare dropdown.
// Native: Owns its selected value.
func SelectInput(els ...El) *Element { return compose("SelectInput", nil, els) }

// SearchBar is the frame's persistent search entry.
// Native: The submitted action must carry the live input value, and in a live session the value streams up debounced as it changes.
func SearchBar(els ...El) *Element { return compose("SearchBar", nil, els) }

// Menu is a click-to-open list of actions behind a trigger.
// Native: Owns its open/closed state.
func Menu(els ...El) *Element { return compose("Menu", nil, els) }

// Slider selects a number in a range.
// Native: Displays its own live value beside itself, so output couples to internal state.
func Slider(els ...El) *Element { return compose("Slider", nil, els) }

// RatingControl selects a star rating.
// Native: Owns the selection.
func RatingControl(els ...El) *Element { return compose("RatingControl", nil, els) }

// SeasonSelector picks one season of a series.
// Native: Owns the selected season.
func SeasonSelector(els ...El) *Element { return compose("SeasonSelector", nil, els) }

// ProgressBar shows a linear completion fraction.
// Native: Fill geometry is computed from the value at render.
func ProgressBar(els ...El) *Element { return compose("ProgressBar", nil, els) }

// ProgressRing shows a circular completion fraction with the percentage inside.
// Native: Arc geometry is computed from the value at render.
func ProgressRing(els ...El) *Element { return compose("ProgressRing", nil, els) }

// Skeleton is an animated loading placeholder.
// Native: Expands to a repeated animated shape; the animation is a client concern.
func Skeleton(els ...El) *Element { return compose("Skeleton", nil, els) }

// Player is the playback surface.
// Native: The client owns the decoding pipeline and the transport controls (ADR 0047, ADR 0070). A scrub bar cannot be driven over a network at frame rate.
func Player(src string, els ...El) *Element {
	return compose("Player", map[string]any{"src": src}, els)
}

// ── components ─────────────────────────────────────────────────────────────

// Screen is the root of a server-defined page.
func Screen(els ...El) *Element { return compose("Screen", nil, els) }

// Section is a titled band.
func Section(title string, els ...El) *Element {
	return compose("Section", map[string]any{"title": title}, els)
}

// Carousel is a horizontal snap-scrolling rail.
func Carousel(els ...El) *Element { return compose("Carousel", nil, els) }

// Grid is a responsive auto-fill grid.
func Grid(els ...El) *Element { return compose("Grid", nil, els) }

// Stack arranges children; direction is "horizontal" or "vertical".
func Stack(direction string, gap int, els ...El) *Element {
	return compose("Stack", map[string]any{"direction": direction, "gap": gap}, els)
}

// Hero is a featured banner. Fill its call-to-action row with Actions.
func Hero(title string, els ...El) *Element {
	return compose("HeroBanner", map[string]any{"title": title}, els)
}

// PosterCard renders a work/item card.
func PosterCard(title string, mediaType string, els ...El) *Element {
	return compose("PosterCard", map[string]any{"title": title, "mediaType": mediaType}, els)
}

// Button carries an action; variant is primary/secondary/ghost/danger.
func Button(label string, variant string, els ...El) *Element {
	return compose("Button", map[string]any{"label": label, "variant": variant}, els)
}

// Badge is a small pill; tone is one of the Tone values.
func Badge(label string, tone string, els ...El) *Element {
	return compose("Badge", map[string]any{"label": label, "tone": tone}, els)
}

// Banner is an inline message; tone is one of the Tone values.
func Banner(message string, tone string, els ...El) *Element {
	return compose("Banner", map[string]any{"message": message, "tone": tone}, els)
}

// DetailHeader renders a node's metadata (title, meta, genres).
func DetailHeader(title string, els ...El) *Element {
	return compose("DetailHeader", map[string]any{"title": title}, els)
}

// EpisodeRow renders one episode under a season.
func EpisodeRow(title string, els ...El) *Element {
	return compose("EpisodeRow", map[string]any{"title": title}, els)
}

// PersonChip is a cast/crew chip.
func PersonChip(name string, els ...El) *Element {
	return compose("PersonChip", map[string]any{"name": name}, els)
}

// GenreTag is a genre chip.
func GenreTag(label string, els ...El) *Element {
	return compose("GenreTag", map[string]any{"label": label}, els)
}

// EmptyState is a titled empty placeholder, with an optional explanation beneath it and a call to action.
func EmptyState(icon string, title string, els ...El) *Element {
	return compose("EmptyState", map[string]any{"icon": icon, "title": title}, els)
}

// AppShell is the application frame (ADR 0031): the brand bar, the nav and the region the current screen renders into.
func AppShell(title string, els ...El) *Element {
	return compose("AppShell", map[string]any{"title": title}, els)
}

// DetailHero is a title's cinematic header — backdrop, logo and the actions docked over it.
func DetailHero(title string, els ...El) *Element {
	return compose("DetailHero", map[string]any{"title": title}, els)
}

// Divider is a rule, optionally labelled.
func Divider(els ...El) *Element { return compose("Divider", nil, els) }

// ErrorState renders a Platform error category as something a person can act on.
func ErrorState(category string, els ...El) *Element {
	return compose("ErrorState", map[string]any{"category": category}, els)
}

// ExtensionCard is one extension module — what it is, what it can do, and where its bytes come from (ADR 0081).
func ExtensionCard(name string, els ...El) *Element {
	return compose("ExtensionCard", map[string]any{"name": name}, els)
}

// IconButton is a Button reduced to its icon; the label stays for assistive tech.
func IconButton(icon string, label string, variant string, els ...El) *Element {
	return compose("IconButton", map[string]any{"icon": icon, "label": label, "variant": variant}, els)
}

// InfoPanel is a docked facts panel — a rating and a run of label/value rows. The mockups draw a control under it ("Change device"); it is not here because Mosaic has no device registry to change between, and a panel is the wrong place to learn that.
func InfoPanel(els ...El) *Element { return compose("InfoPanel", nil, els) }

// FactCard is one labelled card in a row of technical facts — what a release is, how it will be delivered, where its metadata came from. Distinct from InfoPanel because the shape is different and so is the job: a panel answers about the title in label/value pairs, a card states three short facts about one aspect of it and sits in a grid of siblings.
func FactCard(label string, els ...El) *Element {
	return compose("FactCard", map[string]any{"label": label}, els)
}

// MediaTile is a landscape card for episodes and continue-watching.
func MediaTile(title string, els ...El) *Element {
	return compose("MediaTile", map[string]any{"title": title}, els)
}

// Pagination is a prev/next pair. The server supplies both targets; the client does no arithmetic.
func Pagination(els ...El) *Element { return compose("Pagination", nil, els) }

// PlaybackBar is the resume strip for something already started.
func PlaybackBar(title string, els ...El) *Element {
	return compose("PlaybackBar", map[string]any{"title": title}, els)
}

// RelatedRail is a titled rail that says so when it is empty.
func RelatedRail(title string, els ...El) *Element {
	return compose("RelatedRail", map[string]any{"title": title}, els)
}

// Select is a labelled dropdown over server-supplied options.
func Select(label string, els ...El) *Element {
	return compose("Select", map[string]any{"label": label}, els)
}

// SettingsFrame is the Platform-owned settings chrome (ADR 0038): a nav beside the panel the open section fills.
func SettingsFrame(title string, els ...El) *Element {
	return compose("SettingsFrame", map[string]any{"title": title}, els)
}

// SetupFrame is the first-boot wizard's frame (ADR 0098) — a step rail beside the step being filled in. It is a frame rather than a one-off panel because the design has six steps and Mosaic can answer one; the shape is right for the others as the capability behind them arrives.
func SetupFrame(title string, els ...El) *Element {
	return compose("SetupFrame", map[string]any{"title": title}, els)
}

// SignInPanel is the screen drawn before there is a session (ADR 0097) — the brand, a welcome, and a form on a lit card. It is a component like any other because a Platform that is refusing to authenticate you is still answering; the client's own hand-written UI is for the states where it cannot.
func SignInPanel(title string, els ...El) *Element {
	return compose("SignInPanel", map[string]any{"title": title}, els)
}

// SettingsRow is one line of a settings panel — a label, an optional explanation of what it does, and a control or a value on the right. It is the workhorse of every panel in the design, which is why it is a component rather than a Stack assembled per screen: a panel that builds its own rows is a panel that drifts from the others.
func SettingsRow(label string, els ...El) *Element {
	return compose("SettingsRow", map[string]any{"label": label}, els)
}

// SettingsNavGroup is one labelled run of settings nav rows.
func SettingsNavGroup(label string, els ...El) *Element {
	return compose("SettingsNavGroup", map[string]any{"label": label}, els)
}

// SettingsNavItem is one settings nav row. The server marks the active one — it is the side that knows the params (ADR 0039).
func SettingsNavItem(label string, icon string, els ...El) *Element {
	return compose("SettingsNavItem", map[string]any{"label": label, "icon": icon}, els)
}

// SourcePicker lists the resolved sources for a Part.
func SourcePicker(els ...El) *Element { return compose("SourcePicker", nil, els) }

// StatusIndicator is a coloured dot with a label.
func StatusIndicator(label string, tone string, els ...El) *Element {
	return compose("StatusIndicator", map[string]any{"label": label, "tone": tone}, els)
}

// TextField is a labelled text input with optional help.
func TextField(label string, els ...El) *Element {
	return compose("TextField", map[string]any{"label": label}, els)
}

// Toggle is a switch with a label. It carries the value it moves TO — the client reports the flip, the server decides what it means.
func Toggle(label string, els ...El) *Element {
	return compose("Toggle", map[string]any{"label": label}, els)
}

// Form is a State scope with a submit control: it declares the fields' variables, hosts them, and emits its submit action with their values merged in. Composed rather than native — it is a State, an Outlet and a button, and nothing about it needs client code.
func Form(els ...El) *Element { return compose("Form", nil, els) }

// Component is the generic constructor for a type without a helper (a standard component like SeasonSelector, or a module's own).
func Component(typ string, els ...El) *Element { return compose(typ, nil, els) }

// ── slots ──────────────────────────────────────────────────────────────────

// Actions fills the "actions" slot (a hero's CTA row).
func Actions(els ...El) El { return Slot("actions", els...) }

// Aside fills the "aside" slot (a hero's docked poster).
func Aside(els ...El) El { return Slot("aside", els...) }

// ActionSlot fills the "action" slot (an empty state's call to action).
func ActionSlot(els ...El) El { return Slot("action", els...) }

// Header fills a screen's "header" slot.
func Header(els ...El) El { return Slot("header", els...) }

// Bleed fills a screen's edge-to-edge "bleed" slot (a cinematic hero).
func Bleed(els ...El) El { return Slot("bleed", els...) }

// Rail fills a hero's "rail" slot.
func Rail(els ...El) El { return Slot("rail", els...) }

// Tags fills a hero's "tags" slot.
func Tags(els ...El) El { return Slot("tags", els...) }

// Nav fills a frame's "nav" slot.
func Nav(els ...El) El { return Slot("nav", els...) }

// FormSlot fills the "form" slot (a sign-in panel's fields and its submit).
func FormSlot(els ...El) El { return Slot("form", els...) }

// Footer fills a frame's "footer" slot (level controls, not sections).
func Footer(els ...El) El { return Slot("footer", els...) }

// Content fills the app frame's "content" region — where the current screen renders.
func Content(els ...El) El { return Slot("content", els...) }

// TopBar fills the app frame's "topbar" slot.
func TopBar(els ...El) El { return Slot("topbar", els...) }

// Account fills the app frame's "account" slot.
func Account(els ...El) El { return Slot("account", els...) }

// ── sugar ──────────────────────────────────────────────────────────────────

// OnTap sets the node's primary action.
func OnTap(v Action) El { return Prop("action", v) }

// Title sets a screen or component title.
func Title(v string) El { return Prop("title", v) }

// Subtitle sets a card/row subtitle.
func Subtitle(v string) El { return Prop("subtitle", v) }

// Poster sets a poster image URL.
func Poster(v string) El { return Prop("poster", v) }

// Backdrop sets a hero backdrop image URL.
func Backdrop(v string) El { return Prop("backdrop", v) }

// Logo sets a hero clearlogo/title-treatment image URL.
func Logo(v string) El { return Prop("logo", v) }

// Overview sets a synopsis/overview string.
func Overview(v string) El { return Prop("overview", v) }

// Message sets the explanation beneath an empty or error state's title. Banner takes its message positionally; every other component that carries one needs this, and without it the emit-side sets the key by string — which is how a prop nothing renders gets shipped.
func Message(v string) El { return Prop("message", v) }

// Progress sets a 0..1 watched fraction.
func Progress(v float64) El { return Prop("progress", v) }

// BadgeText sets a corner badge on a card.
func BadgeText(v string) El { return Prop("badge", v) }

// ActionLabel sets a Section's "see all" action label (paired with OnTap).
func ActionLabel(v string) El { return Prop("actionLabel", v) }

// Meta sets a hero's meta line (year, type, rating).
func Meta(v ...string) El { return Prop("meta", v) }

// Genres sets a DetailHeader's genre list.
func Genres(v ...string) El { return Prop("genres", v) }

// ResumeAt sets the position in seconds a Player starts from (ADR 0046).
func ResumeAt(v float64) El { return Prop("resumeAt", v) }

// MimeType sets the media type a Player should expect, so a client can pick a pipeline before it fetches.
func MimeType(v string) El { return Prop("mimeType", v) }

// NodeID names the item a Player is playing, so the client can report its position back against it (ADR 0046).
func NodeID(v string) El { return Prop("nodeId", v) }

// PartID names the release a Player is playing, recorded with the position so a resume returns to the same encode (ADR 0046).
func PartID(v string) El { return Prop("partId", v) }

// Disabled greys a control and stops it emitting.
func Disabled(v bool) El { return Prop("disabled", v) }

// IconName names the glyph a control or row shows. It is not called Icon because Icon is the primitive that renders a glyph as a node of its own; this sets the `icon` prop of something that draws one.
func IconName(v string) El { return Prop("icon", v) }

// ItemWidth fixes a carousel's track width in px.
func ItemWidth(v int) El { return Prop("itemWidth", v) }

// Gap sets the space token between a container's children. Stack takes it positionally; a Grid that wants something other than its default says so with this.
func Gap(v int) El { return Prop("gap", v) }

// MinColumnWidth is a grid's smallest column before it reflows, in px.
func MinColumnWidth(v int) El { return Prop("minColumnWidth", v) }

// Rating sets a displayed score.
func Rating(v string) El { return Prop("rating", v) }

// RatingLabel is the source a rating came from.
func RatingLabel(v string) El { return Prop("ratingLabel", v) }

// Year sets a release year.
func Year(v string) El { return Prop("year", v) }

// Index is an episode's place in its series as the design writes it — "S2 E7". A string rather than the episode number, because the season is half the answer and a row that says only "7" is ambiguous the moment a season control sits above it.
func Index(v string) El { return Prop("index", v) }

// Runtime is a human-readable duration.
func Runtime(v string) El { return Prop("runtime", v) }

// Thumbnail sets a row's still image.
func Thumbnail(v string) El { return Prop("thumbnail", v) }

// Watched marks an episode as already seen.
func Watched(v bool) El { return Prop("watched", v) }

// Credits sets a hero's crew line — "Created by X · Directed by Y". One string rather than a list, because it is one sentence with the source's own separators in it; a list would make the joiner a client decision and the client has no way to know whether "and" or "·" is right.
func Credits(v string) El { return Prop("credits", v) }

// Quality is a release's resolution and dynamic range as one phrase — "4K HDR", "1080p". Display-only: it names what a viewer would recognise, not what a decision engine ranks on.
func Quality(v string) El { return Prop("quality", v) }

// Lines are a fact card's body, one short statement per line. Separate from Meta because Meta's entries are pills on one row and these are stacked sentences.
func Lines(v ...string) El { return Prop("lines", v) }

// PinAction keeps a Section's onward link visible instead of revealing it on hover. A rail whose heading is the only way into a catalog cannot hide that link behind a pointer, which no remote control has.
func PinAction(v bool) El { return Prop("pinAction", v) }

// Kicker is the eyebrow line above a hero's title.
func Kicker(v string) El { return Prop("kicker", v) }

// NativeTitle is the original-language title shown beside the localised one.
func NativeTitle(v string) El { return Prop("nativeTitle", v) }

// ProgressLabel describes progress in words ("24m left").
func ProgressLabel(v string) El { return Prop("progressLabel", v) }

// ShowTags reveals a hero's tag row.
func ShowTags(v bool) El { return Prop("showTags", v) }

// OverlayTitle lays a tile's title over its artwork instead of beneath it, for a card that is mostly image — the hero's up-next dock. Off by default, because a title on the picture is only legible when the tile is large enough to carry a scrim under it.
func OverlayTitle(v bool) El { return Prop("overlayTitle", v) }

// Avatar sets a person's portrait.
func Avatar(v string) El { return Prop("avatar", v) }

// Role is a person's part — a character, or a crew credit.
func Role(v string) El { return Prop("role", v) }

// Align sets a stack's cross-axis alignment.
func Align(v string) El { return Prop("align", v) }

// Justify sets a stack's main-axis distribution.
func Justify(v string) El { return Prop("justify", v) }

// Wrap lets a stack run onto more than one line.
func Wrap(v bool) El { return Prop("wrap", v) }

// Retry is what an error state's try-again control emits.
func Retry(v Action) El { return Prop("retry", v) }

// Rows are an info panel's label/value pairs.
func Rows(v []any) El { return Prop("rows", v) }

// Sources are the resolved streams a picker offers.
func Sources(v []any) El { return Prop("sources", v) }

// Options are a select's choices.
func Options(v []any) El { return Prop("options", v) }

// Capabilities are the provider roles a module declares, as chips.
func Capabilities(v []any) El { return Prop("capabilities", v) }

// Summary is a card's one-line description.
func Summary(v string) El { return Prop("summary", v) }

// Value is a field's current value.
func Value(v string) El { return Prop("value", v) }

// Placeholder is a field's empty-state hint.
func Placeholder(v string) El { return Prop("placeholder", v) }

// Help is the note under a field.
func Help(v string) El { return Prop("help", v) }

// InputType selects the keyboard/validation a field asks for.
func InputType(v string) El { return Prop("inputType", v) }

// Chrome selects which frame the app shell draws: "media" — the floating pills over a full-bleed hero — or "admin", the solid bar the settings side of the app wears. Named rather than a boolean because the two are different rooms in the same building, and a third (a player, a setup wizard) is a case rather than a second flag.
func Chrome(v string) El { return Prop("chrome", v) }

// Breadcrumb is the trail after the brand in the admin chrome — "/ Settings". It says where you are on a side of the app that has no hero to say it for you.
func Breadcrumb(v string) El { return Prop("breadcrumb", v) }

// Brand is the install's name for itself, drawn where a screen has no chrome to carry it.
func Brand(v string) El { return Prop("brand", v) }

// Step is where you are in a sequence — "Step 1 of 6".
func Step(v string) El { return Prop("step", v) }

// Footnote is the quiet line at the foot of a rail, saying what a screen does not oblige you to decide now.
func Footnote(v string) El { return Prop("footnote", v) }

// Lead is the sentence under a panel's heading saying what the panel is for. Distinct from Summary, which explains one row.
func Lead(v string) El { return Prop("lead", v) }

// Heading titles a frame's panel.
func Heading(v string) El { return Prop("heading", v) }

// Selected says a section was asked for rather than defaulted to — what lets one payload drill down on a phone and show two panes on a desktop.
func Selected(v bool) El { return Prop("selected", v) }

// Indent nests a nav row under the one above it — an installed extension beneath the store it came from. One list that reads as a hierarchy rather than two lists.
func Indent(v bool) El { return Prop("indent", v) }

// Active marks the open nav row.
func Active(v bool) El { return Prop("active", v) }

// HasPrev enables a pagination's previous control.
func HasPrev(v bool) El { return Prop("hasPrev", v) }

// HasNext enables a pagination's next control.
func HasNext(v bool) El { return Prop("hasNext", v) }

// PrevAction is what a pagination's previous control emits.
func PrevAction(v Action) El { return Prop("prevAction", v) }

// NextAction is what a pagination's next control emits.
func NextAction(v Action) El { return Prop("nextAction", v) }

// On is a switch's state. Distinct from Value, which is a field's text: one prop key cannot be a string in one component and a boolean in another, and a switch that read \"true\" as text would render on for the string \"false\" too.
func On(v bool) El { return Prop("on", v) }

// Origin is where a thing came from — an extension's id, version and repository. Distinct from Meta, which is a hero's variadic meta line: the same key cannot be a string in one component and a list in another.
func Origin(v string) El { return Prop("origin", v) }

// Vars declares a State scope's variables — each a name, a type ("string", "number" or "boolean") and an initial value. Declared rather than inferred: a client must know a name exists before anything writes to it, and must know what to coerce a written value to.
func Vars(v []any) El { return Prop("vars", v) }

// Name is a field's name in the enclosing State scope.
func Name(v string) El { return Prop("name", v) }

// SubmitAction is what a Form emits when it is submitted, with the scope's values merged into its input.
func SubmitAction(v Action) El { return Prop("submitAction", v) }

// SubmitLabel is the text on a form's submit control.
func SubmitLabel(v string) El { return Prop("submitLabel", v) }

// Busy marks a form as awaiting its submission's result.
func Busy(v bool) El { return Prop("busy", v) }

// Error is a form-level failure message, distinct from a field's own.
func Error(v string) El { return Prop("error", v) }

// OnAppear is emitted the first time this node becomes visible on screen. The server decides what that means by choosing the action; a client never reports anything it was not asked to.
func OnAppear(v Action) El { return Prop("onAppear", v) }

// OnDisappear is emitted when this node leaves the screen, having been visible.
func OnDisappear(v Action) El { return Prop("onDisappear", v) }

// A11yLabel is the accessible name, for when the visible content is not one — an icon-only control, an image that carries meaning. It is deliberately not `label`: a visible label and an accessible name are different things, and one key meaning both is how a control ends up announced as its own caption.
func A11yLabel(v string) El { return Prop("a11yLabel", v) }

// HeadingLevel is 1-6, the depth of a heading in the screen's outline. Stated rather than inferred from text size, because size is a design decision and outline depth is a structural one — and a screen reader navigates the second.
func HeadingLevel(v int) El { return Prop("headingLevel", v) }

// Live marks a region whose changes should be announced: "polite" waits for a pause, "assertive" interrupts. Anything else is not announced.
func Live(v string) El { return Prop("live", v) }

// Focusable marks a node that can take focus. Stated rather than inferred from interactivity: a card that navigates is focusable, and so is a heading a TV viewer needs to land on to read, and only the emit-side knows which.
func Focusable(v bool) El { return Prop("focusable", v) }

// FocusGroup makes this node's focusable descendants one stop in the tab order, moved between with the arrow keys — the roving pattern. A rail of forty cards is one stop, not forty.
func FocusGroup(v bool) El { return Prop("focusGroup", v) }

// InitialFocus asks for focus when this node first appears. At most one per region wins; a screen naming two is stating a preference it does not have.
func InitialFocus(v bool) El { return Prop("initialFocus", v) }

// NextFocus overrides where focus goes from here, per direction — {up,down,left,right} to node ids. It is an override, not the mechanism: a client works out the rest geometrically, and this is for the cases geometry gets wrong.
func NextFocus(v map[string]any) El { return Prop("nextFocus", v) }

// HasMore says this list is a page of something longer. It is the server's statement, not the client's inference: a page that happens to be full is not evidence there is another one, and a client guessing from the count asks for a page that does not exist.
func HasMore(v bool) El { return Prop("hasMore", v) }

// LoadMore is what fetches the next page. It carries whatever cursor the server needs, because only the server knows what 'next' means for this list — a skip count here, a token elsewhere.
func LoadMore(v Action) El { return Prop("loadMore", v) }

// ── bound sugar ────────────────────────────────────────────────────────────
// The same props, set to a binding the client resolves where the node renders
// rather than to a value decided now. One per helper, generated, because a
// prop set by string is the failure this contract keeps having: ui.Subtitle on
// a Stack drew nothing for a screen's whole life, and Prop("title", Bind(…))
// would put every bound prop back on that footing.

// BindOnTap sets "action" from the named path instead of from a value.
func BindOnTap(path string) El { return Prop("action", sdui.Bind(path)) }

// BindTitle sets "title" from the named path instead of from a value.
func BindTitle(path string) El { return Prop("title", sdui.Bind(path)) }

// BindSubtitle sets "subtitle" from the named path instead of from a value.
func BindSubtitle(path string) El { return Prop("subtitle", sdui.Bind(path)) }

// BindPoster sets "poster" from the named path instead of from a value.
func BindPoster(path string) El { return Prop("poster", sdui.Bind(path)) }

// BindBackdrop sets "backdrop" from the named path instead of from a value.
func BindBackdrop(path string) El { return Prop("backdrop", sdui.Bind(path)) }

// BindLogo sets "logo" from the named path instead of from a value.
func BindLogo(path string) El { return Prop("logo", sdui.Bind(path)) }

// BindOverview sets "overview" from the named path instead of from a value.
func BindOverview(path string) El { return Prop("overview", sdui.Bind(path)) }

// BindMessage sets "message" from the named path instead of from a value.
func BindMessage(path string) El { return Prop("message", sdui.Bind(path)) }

// BindProgress sets "progress" from the named path instead of from a value.
func BindProgress(path string) El { return Prop("progress", sdui.Bind(path)) }

// BindBadgeText sets "badge" from the named path instead of from a value.
func BindBadgeText(path string) El { return Prop("badge", sdui.Bind(path)) }

// BindActionLabel sets "actionLabel" from the named path instead of from a value.
func BindActionLabel(path string) El { return Prop("actionLabel", sdui.Bind(path)) }

// BindMeta sets "meta" from the named path instead of from a value.
func BindMeta(path string) El { return Prop("meta", sdui.Bind(path)) }

// BindGenres sets "genres" from the named path instead of from a value.
func BindGenres(path string) El { return Prop("genres", sdui.Bind(path)) }

// BindResumeAt sets "resumeAt" from the named path instead of from a value.
func BindResumeAt(path string) El { return Prop("resumeAt", sdui.Bind(path)) }

// BindMimeType sets "mimeType" from the named path instead of from a value.
func BindMimeType(path string) El { return Prop("mimeType", sdui.Bind(path)) }

// BindNodeID sets "nodeId" from the named path instead of from a value.
func BindNodeID(path string) El { return Prop("nodeId", sdui.Bind(path)) }

// BindPartID sets "partId" from the named path instead of from a value.
func BindPartID(path string) El { return Prop("partId", sdui.Bind(path)) }

// BindDisabled sets "disabled" from the named path instead of from a value.
func BindDisabled(path string) El { return Prop("disabled", sdui.Bind(path)) }

// BindIconName sets "icon" from the named path instead of from a value.
func BindIconName(path string) El { return Prop("icon", sdui.Bind(path)) }

// BindItemWidth sets "itemWidth" from the named path instead of from a value.
func BindItemWidth(path string) El { return Prop("itemWidth", sdui.Bind(path)) }

// BindGap sets "gap" from the named path instead of from a value.
func BindGap(path string) El { return Prop("gap", sdui.Bind(path)) }

// BindMinColumnWidth sets "minColumnWidth" from the named path instead of from a value.
func BindMinColumnWidth(path string) El { return Prop("minColumnWidth", sdui.Bind(path)) }

// BindRating sets "rating" from the named path instead of from a value.
func BindRating(path string) El { return Prop("rating", sdui.Bind(path)) }

// BindRatingLabel sets "ratingLabel" from the named path instead of from a value.
func BindRatingLabel(path string) El { return Prop("ratingLabel", sdui.Bind(path)) }

// BindYear sets "year" from the named path instead of from a value.
func BindYear(path string) El { return Prop("year", sdui.Bind(path)) }

// BindIndex sets "index" from the named path instead of from a value.
func BindIndex(path string) El { return Prop("index", sdui.Bind(path)) }

// BindRuntime sets "runtime" from the named path instead of from a value.
func BindRuntime(path string) El { return Prop("runtime", sdui.Bind(path)) }

// BindThumbnail sets "thumbnail" from the named path instead of from a value.
func BindThumbnail(path string) El { return Prop("thumbnail", sdui.Bind(path)) }

// BindWatched sets "watched" from the named path instead of from a value.
func BindWatched(path string) El { return Prop("watched", sdui.Bind(path)) }

// BindCredits sets "credits" from the named path instead of from a value.
func BindCredits(path string) El { return Prop("credits", sdui.Bind(path)) }

// BindQuality sets "quality" from the named path instead of from a value.
func BindQuality(path string) El { return Prop("quality", sdui.Bind(path)) }

// BindLines sets "lines" from the named path instead of from a value.
func BindLines(path string) El { return Prop("lines", sdui.Bind(path)) }

// BindPinAction sets "pinAction" from the named path instead of from a value.
func BindPinAction(path string) El { return Prop("pinAction", sdui.Bind(path)) }

// BindKicker sets "kicker" from the named path instead of from a value.
func BindKicker(path string) El { return Prop("kicker", sdui.Bind(path)) }

// BindNativeTitle sets "nativeTitle" from the named path instead of from a value.
func BindNativeTitle(path string) El { return Prop("nativeTitle", sdui.Bind(path)) }

// BindProgressLabel sets "progressLabel" from the named path instead of from a value.
func BindProgressLabel(path string) El { return Prop("progressLabel", sdui.Bind(path)) }

// BindShowTags sets "showTags" from the named path instead of from a value.
func BindShowTags(path string) El { return Prop("showTags", sdui.Bind(path)) }

// BindOverlayTitle sets "overlayTitle" from the named path instead of from a value.
func BindOverlayTitle(path string) El { return Prop("overlayTitle", sdui.Bind(path)) }

// BindAvatar sets "avatar" from the named path instead of from a value.
func BindAvatar(path string) El { return Prop("avatar", sdui.Bind(path)) }

// BindRole sets "role" from the named path instead of from a value.
func BindRole(path string) El { return Prop("role", sdui.Bind(path)) }

// BindAlign sets "align" from the named path instead of from a value.
func BindAlign(path string) El { return Prop("align", sdui.Bind(path)) }

// BindJustify sets "justify" from the named path instead of from a value.
func BindJustify(path string) El { return Prop("justify", sdui.Bind(path)) }

// BindWrap sets "wrap" from the named path instead of from a value.
func BindWrap(path string) El { return Prop("wrap", sdui.Bind(path)) }

// BindRetry sets "retry" from the named path instead of from a value.
func BindRetry(path string) El { return Prop("retry", sdui.Bind(path)) }

// BindRows sets "rows" from the named path instead of from a value.
func BindRows(path string) El { return Prop("rows", sdui.Bind(path)) }

// BindSources sets "sources" from the named path instead of from a value.
func BindSources(path string) El { return Prop("sources", sdui.Bind(path)) }

// BindOptions sets "options" from the named path instead of from a value.
func BindOptions(path string) El { return Prop("options", sdui.Bind(path)) }

// BindCapabilities sets "capabilities" from the named path instead of from a value.
func BindCapabilities(path string) El { return Prop("capabilities", sdui.Bind(path)) }

// BindSummary sets "summary" from the named path instead of from a value.
func BindSummary(path string) El { return Prop("summary", sdui.Bind(path)) }

// BindValue sets "value" from the named path instead of from a value.
func BindValue(path string) El { return Prop("value", sdui.Bind(path)) }

// BindPlaceholder sets "placeholder" from the named path instead of from a value.
func BindPlaceholder(path string) El { return Prop("placeholder", sdui.Bind(path)) }

// BindHelp sets "help" from the named path instead of from a value.
func BindHelp(path string) El { return Prop("help", sdui.Bind(path)) }

// BindInputType sets "inputType" from the named path instead of from a value.
func BindInputType(path string) El { return Prop("inputType", sdui.Bind(path)) }

// BindChrome sets "chrome" from the named path instead of from a value.
func BindChrome(path string) El { return Prop("chrome", sdui.Bind(path)) }

// BindBreadcrumb sets "breadcrumb" from the named path instead of from a value.
func BindBreadcrumb(path string) El { return Prop("breadcrumb", sdui.Bind(path)) }

// BindBrand sets "brand" from the named path instead of from a value.
func BindBrand(path string) El { return Prop("brand", sdui.Bind(path)) }

// BindStep sets "step" from the named path instead of from a value.
func BindStep(path string) El { return Prop("step", sdui.Bind(path)) }

// BindFootnote sets "footnote" from the named path instead of from a value.
func BindFootnote(path string) El { return Prop("footnote", sdui.Bind(path)) }

// BindLead sets "lead" from the named path instead of from a value.
func BindLead(path string) El { return Prop("lead", sdui.Bind(path)) }

// BindHeading sets "heading" from the named path instead of from a value.
func BindHeading(path string) El { return Prop("heading", sdui.Bind(path)) }

// BindSelected sets "selected" from the named path instead of from a value.
func BindSelected(path string) El { return Prop("selected", sdui.Bind(path)) }

// BindIndent sets "indent" from the named path instead of from a value.
func BindIndent(path string) El { return Prop("indent", sdui.Bind(path)) }

// BindActive sets "active" from the named path instead of from a value.
func BindActive(path string) El { return Prop("active", sdui.Bind(path)) }

// BindHasPrev sets "hasPrev" from the named path instead of from a value.
func BindHasPrev(path string) El { return Prop("hasPrev", sdui.Bind(path)) }

// BindHasNext sets "hasNext" from the named path instead of from a value.
func BindHasNext(path string) El { return Prop("hasNext", sdui.Bind(path)) }

// BindPrevAction sets "prevAction" from the named path instead of from a value.
func BindPrevAction(path string) El { return Prop("prevAction", sdui.Bind(path)) }

// BindNextAction sets "nextAction" from the named path instead of from a value.
func BindNextAction(path string) El { return Prop("nextAction", sdui.Bind(path)) }

// BindOn sets "on" from the named path instead of from a value.
func BindOn(path string) El { return Prop("on", sdui.Bind(path)) }

// BindOrigin sets "origin" from the named path instead of from a value.
func BindOrigin(path string) El { return Prop("origin", sdui.Bind(path)) }

// BindVars sets "vars" from the named path instead of from a value.
func BindVars(path string) El { return Prop("vars", sdui.Bind(path)) }

// BindName sets "name" from the named path instead of from a value.
func BindName(path string) El { return Prop("name", sdui.Bind(path)) }

// BindSubmitAction sets "submitAction" from the named path instead of from a value.
func BindSubmitAction(path string) El { return Prop("submitAction", sdui.Bind(path)) }

// BindSubmitLabel sets "submitLabel" from the named path instead of from a value.
func BindSubmitLabel(path string) El { return Prop("submitLabel", sdui.Bind(path)) }

// BindBusy sets "busy" from the named path instead of from a value.
func BindBusy(path string) El { return Prop("busy", sdui.Bind(path)) }

// BindError sets "error" from the named path instead of from a value.
func BindError(path string) El { return Prop("error", sdui.Bind(path)) }

// BindOnAppear sets "onAppear" from the named path instead of from a value.
func BindOnAppear(path string) El { return Prop("onAppear", sdui.Bind(path)) }

// BindOnDisappear sets "onDisappear" from the named path instead of from a value.
func BindOnDisappear(path string) El { return Prop("onDisappear", sdui.Bind(path)) }

// BindA11yLabel sets "a11yLabel" from the named path instead of from a value.
func BindA11yLabel(path string) El { return Prop("a11yLabel", sdui.Bind(path)) }

// BindHeadingLevel sets "headingLevel" from the named path instead of from a value.
func BindHeadingLevel(path string) El { return Prop("headingLevel", sdui.Bind(path)) }

// BindLive sets "live" from the named path instead of from a value.
func BindLive(path string) El { return Prop("live", sdui.Bind(path)) }

// BindFocusable sets "focusable" from the named path instead of from a value.
func BindFocusable(path string) El { return Prop("focusable", sdui.Bind(path)) }

// BindFocusGroup sets "focusGroup" from the named path instead of from a value.
func BindFocusGroup(path string) El { return Prop("focusGroup", sdui.Bind(path)) }

// BindInitialFocus sets "initialFocus" from the named path instead of from a value.
func BindInitialFocus(path string) El { return Prop("initialFocus", sdui.Bind(path)) }

// BindNextFocus sets "nextFocus" from the named path instead of from a value.
func BindNextFocus(path string) El { return Prop("nextFocus", sdui.Bind(path)) }

// BindHasMore sets "hasMore" from the named path instead of from a value.
func BindHasMore(path string) El { return Prop("hasMore", sdui.Bind(path)) }

// BindLoadMore sets "loadMore" from the named path instead of from a value.
func BindLoadMore(path string) El { return Prop("loadMore", sdui.Bind(path)) }

// Tone values (the open-bag string encoding), re-exported from the producer binding.
const (
	ToneNeutral = sdui.ToneNeutral
	ToneAccent  = sdui.ToneAccent
	ToneSuccess = sdui.ToneSuccess
	ToneWarning = sdui.ToneWarning
	ToneDanger  = sdui.ToneDanger
	ToneInfo    = sdui.ToneInfo
)

// Action constructors, re-exported from the producer binding; they ride the open
// props bag as JSON (ADR 0044).
var (
	Navigate     = sdui.Navigate
	Invoke       = sdui.Invoke
	Play         = sdui.Play
	OpenURL      = sdui.OpenURL
	Back         = sdui.Back
	Query        = sdui.Query
	OpenOverlay  = sdui.OpenOverlay
	CloseOverlay = sdui.CloseOverlay
	Toast        = sdui.Toast
	Sequence     = sdui.Sequence
	SetValue     = sdui.SetValue
	Submit       = sdui.Submit
)
