// Code generated by tools/genui from ui.spec.json. DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 the Mosaic authors

package sdui

// VocabularyVersion is the version a client declares it implements. Additive
// growth is a minor bump; removing or changing the meaning of a primitive, a
// prop or an action is a major one.
const VocabularyVersion = "1.1.0"

// TypeSeparator divides a module's id from its own type name. Core types are
// unprefixed and may never contain it; a module's are moduleId:type. Two
// modules could otherwise both call a component StatChip, and one could call
// it PosterCard and take the core component's place.
const TypeSeparator = ":"

// Node type names — the primitive tier.
const (
	TypeBox            = "Box"
	TypeText           = "Text"
	TypeImage          = "Image"
	TypeIcon           = "Icon"
	TypePressable      = "Pressable"
	TypeSpacer         = "Spacer"
	TypeFragment       = "Fragment"
	TypeOutlet         = "Outlet"
	TypeNavItem        = "NavItem"
	TypeNavBar         = "NavBar"
	TypeTabs           = "Tabs"
	TypeRotator        = "Rotator"
	TypeTextInput      = "TextInput"
	TypeSwitch         = "Switch"
	TypeSelectInput    = "SelectInput"
	TypeForm           = "Form"
	TypeSubmitField    = "SubmitField"
	TypeSearchBar      = "SearchBar"
	TypeMenu           = "Menu"
	TypeSlider         = "Slider"
	TypeRatingControl  = "RatingControl"
	TypeSeasonSelector = "SeasonSelector"
	TypeProgressBar    = "ProgressBar"
	TypeProgressRing   = "ProgressRing"
	TypeSkeleton       = "Skeleton"
	TypePlayer         = "Player"
)

// Node type names — the component tier (definitions/*.json).
const (
	TypeScreen           = "Screen"
	TypeSection          = "Section"
	TypeCarousel         = "Carousel"
	TypeGrid             = "Grid"
	TypeStack            = "Stack"
	TypeHeroBanner       = "HeroBanner"
	TypePosterCard       = "PosterCard"
	TypeButton           = "Button"
	TypeBadge            = "Badge"
	TypeBanner           = "Banner"
	TypeDetailHeader     = "DetailHeader"
	TypeEpisodeRow       = "EpisodeRow"
	TypePersonChip       = "PersonChip"
	TypeGenreTag         = "GenreTag"
	TypeEmptyState       = "EmptyState"
	TypeAppShell         = "AppShell"
	TypeDetailHero       = "DetailHero"
	TypeDivider          = "Divider"
	TypeErrorState       = "ErrorState"
	TypeExtensionCard    = "ExtensionCard"
	TypeIconButton       = "IconButton"
	TypeInfoPanel        = "InfoPanel"
	TypeMediaTile        = "MediaTile"
	TypePagination       = "Pagination"
	TypePlaybackBar      = "PlaybackBar"
	TypeRelatedRail      = "RelatedRail"
	TypeSelect           = "Select"
	TypeSettingsFrame    = "SettingsFrame"
	TypeSettingsNavGroup = "SettingsNavGroup"
	TypeSettingsNavItem  = "SettingsNavItem"
	TypeSourcePicker     = "SourcePicker"
	TypeStatusIndicator  = "StatusIndicator"
	TypeTextField        = "TextField"
	TypeToggle           = "Toggle"
)

// Action kinds — the JSON discriminator values.
const (
	KindNavigate     = "navigate"
	KindInvoke       = "invoke"
	KindPlayPart     = "playPart"
	KindOpenURL      = "openUrl"
	KindBack         = "back"
	KindQuery        = "query"
	KindOpenOverlay  = "openOverlay"
	KindCloseOverlay = "closeOverlay"
	KindToast        = "toast"
	KindSequence     = "sequence"
	KindSetValue     = "setValue"
	KindSubmit       = "submit"
)

// Tones.
const (
	ToneNeutral = "neutral"
	ToneAccent  = "accent"
	ToneSuccess = "success"
	ToneWarning = "warning"
	ToneDanger  = "danger"
	ToneInfo    = "info"
)

// Overlay surfaces.
const (
	SurfaceModal  = "modal"
	SurfaceSheet  = "sheet"
	SurfaceDrawer = "drawer"
)

// Primitives is the native tier as data: what a client must implement, and
// for each one the reason it cannot be a definition.
var Primitives = []PrimitiveSpec{
	{Type: "Box", Tier: "presentational", Doc: "Box is the layout container every composition is built from.", Native: "The irreducible layout leaf. A definition is a tree of primitives, so the base case cannot itself be a definition. It also resolves style.responsive against the live viewport, which is a render-time branch no static tree can carry.", Children: true, Props: []PropSpec{
		{Key: "style", Type: "boxStyle", Doc: "Layout and surface style, including the responsive override."},
	}},
	{Type: "Text", Tier: "presentational", Doc: "Text renders a run of text in a token style. Children render after the text, for inline nesting.", Native: "The irreducible text leaf.", Children: true, Props: []PropSpec{
		{Key: "text", Type: "string", Doc: "The string to render."},
		{Key: "style", Type: "textStyle", Doc: "Variant, weight and colour token."},
	}},
	{Type: "Image", Tier: "presentational", Doc: "Image renders a remote or proxied image with a placeholder fallback.", Native: "Loading a resource, handling decode failure and falling back to a placeholder are client behaviours. It also feeds the art-light sampler, which reads decoded pixels.", Children: false, Props: []PropSpec{
		{Key: "src", Type: "string", Doc: "Image URL. Platform-emitted URLs are artwork-proxy signed."},
		{Key: "alt", Type: "string", Doc: "Alternative text."},
		{Key: "fit", Type: "enum:cover|contain", Doc: "How the image fills its box."},
		{Key: "placeholder", Type: "string", Doc: "Text shown while loading or when the source fails."},
		{Key: "placeholderMode", Type: "enum:label|initials", Doc: "Whether the placeholder renders as a label or as initials."},
		{Key: "artLight", Type: "enum:ambient|focus", Doc: "Publish this image's palette to the acrylic surfaces."},
		{Key: "style", Type: "boxStyle", Doc: "Box style applied to the image frame."},
	}},
	{Type: "Icon", Tier: "presentational", Doc: "Icon renders one glyph from the client's bundled icon set.", Native: "Resolves a name to a vector the client ships. The glyph set is a client asset, not data.", Children: false, Props: []PropSpec{
		{Key: "name", Type: "iconName", Doc: "Icon name from the shared set."},
		{Key: "size", Type: "string|number", Doc: "Rendered size; defaults to 1.2em."},
		{Key: "color", Type: "colorToken", Doc: "Colour token override."},
	}},
	{Type: "Pressable", Tier: "interactive", Doc: "Pressable makes its subtree activate an Action.", Native: "Turning a pointer, key or remote-control event into an Action dispatch is client behaviour.", Children: true, Props: []PropSpec{
		{Key: "style", Type: "boxStyle", Doc: "Layout and surface style, including the responsive override."},
		{Key: "action", Type: "action", Doc: "Action emitted on activation."},
		{Key: "disabled", Type: "boolean", Doc: "Refuse activation and render the disabled state."},
		{Key: "lift", Type: "boolean", Doc: "Apply the hover-lift affordance."},
		{Key: "label", Type: "string", Doc: "Accessible label when the subtree carries no text."},
	}},
	{Type: "Spacer", Tier: "presentational", Doc: "Spacer occupies empty space in a stack, fixed or growing.", Native: "An irreducible layout leaf.", Children: false, Props: []PropSpec{
		{Key: "size", Type: "spaceToken", Doc: "Fixed size from the space scale."},
		{Key: "grow", Type: "boolean", Doc: "Absorb the remaining free space instead."},
	}},
	{Type: "Fragment", Tier: "presentational", Doc: "Fragment renders its children with no wrapper of its own.", Native: "A transparent grouping node the expander needs in order to return several nodes where one is expected.", Children: true, Props: []PropSpec{}},
	{Type: "Outlet", Tier: "presentational", Doc: "Outlet marks the point in a definition's template where the caller's slot content is substituted.", Native: "It is the definition expander's own mechanism. A definition defined in terms of Outlet cannot itself be expanded without it, so it must be native.", Children: true, Props: []PropSpec{
		{Key: "name", Type: "string", Doc: "Slot name filled from the caller's slots map."},
	}},
	{Type: "NavItem", Tier: "interactive", Doc: "NavItem is one entry in the app frame's navigation.", Native: "Owns active-route state: it compares the current screen against its own target, which only the client knows.", Children: false, Props: []PropSpec{
		{Key: "label", Type: "string", Doc: "Visible label."},
		{Key: "icon", Type: "iconName", Doc: "Leading icon."},
		{Key: "screen", Type: "string", Doc: "Screen this item marks as active."},
		{Key: "action", Type: "action", Doc: "Action emitted on activation."},
	}},
	{Type: "NavBar", Tier: "interactive", Doc: "NavBar groups NavItems into the frame's responsive navigation.", Native: "Presents as an inline bar or a bottom tab strip depending on the viewport — a render-time branch, not data.", Children: true, Props: []PropSpec{}},
	{Type: "Tabs", Tier: "interactive", Doc: "Tabs shows one panel at a time behind a tab strip. Each tab's content goes in the named slot matching its id, not in the ordered child list — an ordered child is dropped.", Native: "Owns the active tab index.", Children: false, Props: []PropSpec{
		{Key: "tabs", Type: "array:tab", Doc: "Tab descriptors, each an id and a label."},
	}},
	{Type: "Rotator", Tier: "interactive", Doc: "Rotator cross-fades through its children on a timer.", Native: "Owns a timer and derives the active index from it, and republishes the active slide's palette to the acrylic surfaces.", Children: true, Props: []PropSpec{
		{Key: "interval", Type: "number", Doc: "Dwell time per slide in milliseconds."},
	}},
	{Type: "TextInput", Tier: "field", Doc: "TextInput is a bare text entry field.", Native: "Owns its input value between keystroke and submission.", Children: false, Props: []PropSpec{
		{Key: "name", Type: "string", Doc: "Field name under which an enclosing Form collects this value."},
		{Key: "inputType", Type: "string", Doc: "Native input type — text, password, email, number."},
		{Key: "placeholder", Type: "string", Doc: "Placeholder text."},
		{Key: "value", Type: "string", Doc: "Initial value."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "Switch", Tier: "field", Doc: "Switch is a bare on/off control.", Native: "Owns its on/off state.", Children: false, Props: []PropSpec{
		{Key: "name", Type: "string", Doc: "Field name under which an enclosing Form collects this value."},
		{Key: "value", Type: "boolean", Doc: "Initial state."},
		{Key: "action", Type: "action", Doc: "Action emitted on change, for a switch that acts immediately rather than being submitted."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "SelectInput", Tier: "field", Doc: "SelectInput is a bare dropdown.", Native: "Owns its selected value.", Children: false, Props: []PropSpec{
		{Key: "name", Type: "string", Doc: "Field name under which an enclosing Form collects this value."},
		{Key: "options", Type: "array:option", Doc: "Selectable options, each a value and a label."},
		{Key: "value", Type: "string", Doc: "Initially selected value."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "Form", Tier: "field", Doc: "Form collects the values of the fields in its subtree and submits them as one action.", Native: "Aggregates live state across a whole subtree into a single action payload at submit time. No static tree can read its descendants' current values, which is why a multi-field screen was previously impossible to express.", Children: true, Props: []PropSpec{
		{Key: "submitAction", Type: "action", Doc: "Action emitted on submit. Collected field values are merged into its input under each field's name."},
		{Key: "submitLabel", Type: "string", Doc: "Label of the submit control."},
		{Key: "busy", Type: "boolean", Doc: "Render the in-flight state and refuse repeat submission."},
		{Key: "error", Type: "string", Doc: "Server-supplied error to display against the form as a whole."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "SubmitField", Tier: "field", Doc: "SubmitField is a single text field with its own submit control.", Native: "Owns its input value and substitutes it into the action at submit time.", Children: false, Props: []PropSpec{
		{Key: "placeholder", Type: "string", Doc: "Placeholder text."},
		{Key: "submitLabel", Type: "string", Doc: "Label of the submit control."},
		{Key: "action", Type: "action", Doc: "Action emitted on submit, with the literal string \"$value\" replaced by the typed value wherever it appears."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "SearchBar", Tier: "field", Doc: "SearchBar is the frame's persistent search entry.", Native: "The submitted action must carry the live input value, and in a live session the value streams up debounced as it changes.", Children: false, Props: []PropSpec{
		{Key: "placeholder", Type: "string", Doc: "Placeholder text."},
		{Key: "submitScreen", Type: "string", Doc: "Screen navigated to on submit when there is no live session."},
		{Key: "value", Type: "string", Doc: "Initial term."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "Menu", Tier: "interactive", Doc: "Menu is a click-to-open list of actions behind a trigger.", Native: "Owns its open/closed state.", Children: false, Props: []PropSpec{
		{Key: "label", Type: "string", Doc: "Accessible label for the trigger."},
		{Key: "initial", Type: "string", Doc: "Render an avatar-circle trigger showing this initial instead of the overflow glyph."},
		{Key: "items", Type: "array:menuItem", Doc: "Menu entries, each a label with an optional icon, tone and action."},
	}},
	{Type: "Slider", Tier: "field", Doc: "Slider selects a number in a range.", Native: "Displays its own live value beside itself, so output couples to internal state.", Children: false, Props: []PropSpec{
		{Key: "name", Type: "string", Doc: "Field name under which an enclosing Form collects this value."},
		{Key: "label", Type: "string", Doc: "Field label, rendered beside the live value."},
		{Key: "min", Type: "number", Doc: "Lower bound."},
		{Key: "max", Type: "number", Doc: "Upper bound."},
		{Key: "value", Type: "number", Doc: "Initial value."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
	}},
	{Type: "RatingControl", Tier: "field", Doc: "RatingControl selects a star rating.", Native: "Owns the selection.", Children: false, Props: []PropSpec{
		{Key: "name", Type: "string", Doc: "Field name under which an enclosing Form collects this value."},
		{Key: "max", Type: "number", Doc: "Number of stars."},
		{Key: "value", Type: "number", Doc: "Initial rating."},
		{Key: "action", Type: "action", Doc: "Action emitted on change."},
		{Key: "validators", Type: "validators", Doc: "Declarative rules the client enforces before submit. Server-side failures arrive as fieldErrors and render in the same slot."},
		{Key: "visibleWhen", Type: "predicate", Doc: "Structured predicate over sibling field values. Absent means always visible."},
		{Key: "label", Type: "string", Doc: "Field label."},
	}},
	{Type: "SeasonSelector", Tier: "interactive", Doc: "SeasonSelector picks one season of a series.", Native: "Owns the selected season.", Children: false, Props: []PropSpec{
		{Key: "seasons", Type: "array:season", Doc: "Selectable seasons, each an id and a label with an optional action."},
		{Key: "selected", Type: "string", Doc: "Initially selected season id."},
	}},
	{Type: "ProgressBar", Tier: "computed", Doc: "ProgressBar shows a linear completion fraction.", Native: "Fill geometry is computed from the value at render.", Children: false, Props: []PropSpec{
		{Key: "value", Type: "number", Doc: "Completion from 0 to 1."},
		{Key: "tone", Type: "tone", Doc: "Fill tone."},
	}},
	{Type: "ProgressRing", Tier: "computed", Doc: "ProgressRing shows a circular completion fraction with the percentage inside.", Native: "Arc geometry is computed from the value at render.", Children: false, Props: []PropSpec{
		{Key: "value", Type: "number", Doc: "Completion from 0 to 1."},
		{Key: "size", Type: "number", Doc: "Diameter in pixels."},
	}},
	{Type: "Skeleton", Tier: "computed", Doc: "Skeleton is an animated loading placeholder.", Native: "Expands to a repeated animated shape; the animation is a client concern.", Children: false, Props: []PropSpec{
		{Key: "shape", Type: "enum:poster|line|block|circle", Doc: "Placeholder shape."},
		{Key: "count", Type: "number", Doc: "How many to render."},
	}},
	{Type: "Player", Tier: "player", Doc: "Player is the playback surface.", Native: "The client owns the decoding pipeline and the transport controls (ADR 0047, ADR 0070). A scrub bar cannot be driven over a network at frame rate.", Children: false, Props: []PropSpec{
		{Key: "src", Type: "string", Doc: "Playback URL issued by the Platform."},
		{Key: "title", Type: "string", Doc: "Title shown in the player chrome."},
		{Key: "poster", Type: "string", Doc: "Poster shown before the first frame."},
		{Key: "mimeType", Type: "string", Doc: "Container MIME type."},
		{Key: "resumeAt", Type: "number", Doc: "Seconds to seek to once the media is seekable."},
		{Key: "nodeId", Type: "string", Doc: "Content node this playback reports progress against."},
		{Key: "partId", Type: "string", Doc: "Release actually being played."},
	}},
}

// Components is the definition tier: the type names the Platform serves as
// data. A client implements none of them.
var Components = []string{
	"Screen",
	"Section",
	"Carousel",
	"Grid",
	"Stack",
	"HeroBanner",
	"PosterCard",
	"Button",
	"Badge",
	"Banner",
	"DetailHeader",
	"EpisodeRow",
	"PersonChip",
	"GenreTag",
	"EmptyState",
	"AppShell",
	"DetailHero",
	"Divider",
	"ErrorState",
	"ExtensionCard",
	"IconButton",
	"InfoPanel",
	"MediaTile",
	"Pagination",
	"PlaybackBar",
	"RelatedRail",
	"Select",
	"SettingsFrame",
	"SettingsNavGroup",
	"SettingsNavItem",
	"SourcePicker",
	"StatusIndicator",
	"TextField",
	"Toggle",
}

// ActionKinds is every behaviour a client interprets.
var ActionKinds = []ActionSpec{
	{Kind: "navigate", Doc: "Navigate pushes a screen, optionally with params."},
	{Kind: "invoke", Doc: "Invoke runs a server mutation, optionally with input."},
	{Kind: "playPart", Doc: "Play starts playback of a part."},
	{Kind: "openUrl", Doc: "OpenURL opens an external URL (the client validates the scheme)."},
	{Kind: "back", Doc: "Back returns to the previous screen."},
	{Kind: "query", Doc: "Query re-reads a screen's data without changing the route."},
	{Kind: "openOverlay", Doc: "OpenOverlay presents a node as a modal, sheet or drawer."},
	{Kind: "closeOverlay", Doc: "CloseOverlay dismisses the topmost overlay."},
	{Kind: "toast", Doc: "Toast shows a transient message."},
	{Kind: "sequence", Doc: "Sequence runs several actions in order, stopping at the first failure."},
	{Kind: "setValue", Doc: "SetValue writes a value into a named field in the enclosing form scope."},
	{Kind: "submit", Doc: "Submit validates the enclosing form and, if it passes, emits its submitAction with the collected field values merged into the input."},
}

// Validators is the closed field-validation set. Closed on purpose: an open
// set lets the server state a rule the client cannot enforce, which fails open.
var Validators = []ValidatorSpec{
	{Name: "required", Arg: "boolean", Doc: "The field must be non-empty."},
	{Name: "minLength", Arg: "number", Doc: "Minimum length in characters."},
	{Name: "maxLength", Arg: "number", Doc: "Maximum length in characters."},
	{Name: "pattern", Arg: "string", Doc: "RE2 regular expression the value must match. RE2 rather than PCRE so every client can compile it and none can be made to backtrack."},
	{Name: "matches", Arg: "string", Doc: "Another field's name whose value this must equal — the confirm-password case."},
	{Name: "oneOf", Arg: "array:string", Doc: "The value must be one of these."},
}

// Predicates is the closed conditional set — the deliberate alternative to an
// expression language and the evaluator VM one would need.
var Predicates = []PredicateSpec{
	{Name: "equals", Doc: "{field, equals} — the named field's value equals this."},
	{Name: "notEmpty", Doc: "{field, notEmpty: true} — the named field has a value."},
	{Name: "oneOf", Doc: "{field, oneOf: [...]} — the named field is one of these."},
	{Name: "not", Doc: "{not: <predicate>} — negation."},
	{Name: "all", Doc: "{all: [<predicate>...]} — conjunction."},
	{Name: "any", Doc: "{any: [<predicate>...]} — disjunction."},
}
